### ISSUE TITLE
 ImportError: No module named requests

### ISSUE THREAD

**Issue by arjunnaha** [jasperproject/jasper-client#114]
Everytime I run boot.sh from jasper/boot, I get this error message...

```
File "main.py", line 4, in <module>
from conversation import Conversation
File "/home/pi/jasper/client/conversation.py", line 1, in <module>
from notifier import Notifier
File "/home/pi/jasper/client/notifier.py", line 2, in <module>
from modules import Gmail
File "/home/pi/jasper/client/modules/Gmail.py", line 5, in <module>
from app_utils import *
File "/home/pi/jasper/client/modules/app_utils.py", line 5, in <module>
import requests
ImportError: No module named requests
```

I don't really know how to use Jasper. What is the correct way of starting it.

**Comment by PremaPrems** [comment]
$ JASPER_HOME="/home/prem/jasper/client" && python main.py --local
No handlers could be found for logger "client.vocabcompiler"
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    runpy.run_path(script_path, run_name="__main__")
  File "/home/prem/anaconda2/lib/python2.7/runpy.py", line 252, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/home/prem/anaconda2/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/home/prem/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "../jasper.py", line 16, in <module>
    from client.conversation import Conversation
  File "../client/conversation.py", line 3, in <module>
    from notifier import Notifier
  File "../client/notifier.py", line 5, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
ImportError: No module named apscheduler.schedulers.background

This error occured while run the above command.how to i solve this error.
