### ISSUE TITLE
Jasper fails to load playlists via Spotify

### ISSUE THREAD

**Issue by vcx312** [jasperproject/jasper-client#215]
He fails to load the playlist as he says "I'm sorry, I'm having some trouble with that operation" 
There's this, if it's of any help 
ERROR:client.brain:Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 67, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/MPDControl.py", line 47, in handle
    music_mode.handleForever()
  File "/home/pi/jasper/client/modules/MPDControl.py", line 175, in handleForever
    self.mic.say("Playing %s" % self.music.current_song())
  File "/home/pi/jasper/client/modules/MPDControl.py", line 218, in wrap
    return func(self, _default_args, *_default_kwargs)
  File "/home/pi/jasper/client/modules/MPDControl.py", line 296, in current_song
    item = self.client.playlistinfo(int(self.client.status()["song"]))[0]
KeyError: 'song'

**Comment by chill07** [comment]
hello everyone, i'm reopening this very old thread since i have the same issue.i already reinstalled and the problem still persists. 
![17475244_1307115319324007_906910683_o](https://cloud.githubusercontent.com/assets/26640852/24278640/edfdd502-107f-11e7-8b50-9b8b9ce71554.jpg)
i already made mopidy a service and this its status. please help me !!
