### ISSUE TITLE
Jasper on Fedora 20. CMUCLMTK command not found

### ISSUE THREAD

**Issue by MalcolmMielle** [jasperproject/jasper-client#231]
Hello all,

I'm trying to run Jasper on Fedora 20. It might be a stupid question I'm going to ask but I don't really know where to go to ask it other than here.

So I installed most of the dependencies I think but when trying to run Jasper this is what it outputs : 

```
[malcolm@bokkie jasper-client]$ python jasper.py 
No handlers could be found for logger "cmuclmtk"
===========================================================
 JASPER The Talking Computer                               
 Copyright 2013 Shubhro Saha & Charlie Marsh               
===========================================================
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
CRITICAL:cmuclmtk:Can't find CMUCLMTK command 'text2wfreq'! Please check if CMUCLMTK is installed and in your $PATH.
ERROR:vocabcompiler:Error importing CMUCLMTK module. PocketsphinxVocabulary will not work correctly.
Traceback (most recent call last):
  File "/mnt/Data/Mad Maker/Jasper/jasper-client/client/vocabcompiler.py", line 18, in <module>
    import cmuclmtk
  File "/usr/lib/python2.7/site-packages/cmuclmtk/__init__.py", line 64, in <module>
    raise ImportError("CMUCLMTK command(s) missing or not in $PATH.")
ImportError: CMUCLMTK command(s) missing or not in $PATH.
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/mnt/Data/Mad Maker/Jasper/jasper-client/client/vocabcompiler.py", line 157, in compile
    self._compile_vocabulary(phrases)
  File "/mnt/Data/Mad Maker/Jasper/jasper-client/client/vocabcompiler.py", line 263, in _compile_vocabulary
    vocabulary = self._compile_languagemodel(text, self.languagemodel_file)
  File "/mnt/Data/Mad Maker/Jasper/jasper-client/client/vocabcompiler.py", line 284, in _compile_languagemodel
    cmuclmtk.text2vocab(text, vocab_file)
NameError: global name 'cmuclmtk' is not defined
ERROR:root:Error occured!
Traceback (most recent call last):
  File "jasper.py", line 140, in <module>
    app = Jasper()
  File "jasper.py", line 104, in __init__
    stt.PocketSphinxSTT(**stt.PocketSphinxSTT.get_config()),
  File "/mnt/Data/Mad Maker/Jasper/jasper-client/client/stt.py", line 144, in get_config
    config['vocabulary'].compile(vocabcompiler.get_all_phrases())
  File "/mnt/Data/Mad Maker/Jasper/jasper-client/client/vocabcompiler.py", line 165, in compile
    raise e
NameError: global name 'cmuclmtk' is not defined
```

I installed cmuclmtk with pip and I don't really understand why it can't find the CMUCLMTK command above.

Does anyone has an idea on this ?

**Comment by YoungJuleke** [comment]
Still not working, even after following your instructions above...cmuclmtk compiled and installed fine, but...
jules@Poseidon:~/dev/jasper-client/client$ python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cmuclmtk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cmuclmtk

**Comment by Holzhaus** [comment]
@YoungJuleke You need both, CMUCLMTK and the python wrapper. You're missing the latter.
