### ISSUE TITLE
IOError: [Errno Input Overflowed] -9981

### ISSUE THREAD

**Issue by iamhappypappy** [jasperproject/jasper-client#240]
I am able to use Jasper with no problem and ask a couple of questions from the pre-built questions.

After a couple of times I ask questions It errors out with IOError: [Errno Input Overflowed] -9981, I have to restart it and the same thing keeps happening. I can only get a couple of requests and responses then it crashes. 

The file error says 'Cannot schedule new tasks after shutdown'...

Any help please.

**Comment by JonnyAlpha** [comment]
Same issue here i'm afraid. This issue was happening a lot sooner but having had some feedback with an earlier version of Jasper where someone suggested this may have something to do with too many unread emails I extended the seconds in def_init_(Self, profile): in Notifier.py from 30 to 180. This seems to delay the problem.
I checked my email account and found 554 unread emails (I thought I had cleared my emails to see if this cleared the problem ). 
I have just cleared all my unread emails and Jasper has been running whilst I have been typing this but has just crashed :-( 
What happens is that he works fine (albeit with some playback issues in JOKE) and then I get an IOError 9981 Japser then freezes for a while and then finally crashes and exits back to the terminal prompt.

Should I start a new issue or post the debug here. Debug is very similar as posted above apart from the second to last line which reads:
ValueError: unknown string format

**Comment by Holzhaus** [comment]
Can You temporarily comment out your `gmail_address` in your `profile.yml` and try again? This way we can see if it's an issue with the Gmail notifier.

**Comment by JonnyAlpha** [comment]
Holzhaus - I am away on a UNI course for a week so will try this when I get back on Fri.

**Comment by tonylu880042** [comment]
I have same issue, here is my debug log message,
Most of time when I start the Jasper for 1 minute and do nothing with it then the IOError will comes out,
My gmail have lots of unread messages. Is this matter ? 

pi@raspberrypi ~/jasper $ ./jasper.py --debug
===========================================================
 JASPER The Talking Computer                               
 Copyright 2013 Shubhro Saha & Charlie Marsh               
===========================================================
DEBUG:client.diagnose:Checking network connection to server 'www.google.com'...
DEBUG:client.diagnose:Network connection working
DEBUG:__main__:Trying to read config file: '/home/pi/.jasper/profile.yml'
DEBUG:client.diagnose:Checking python import 'pocketsphinx'...
DEBUG:client.diagnose:Python module 'pocketsphinx' found: '/usr/local/lib/python2.7/dist-packages/pocketsphinx.so'
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
DEBUG:client.diagnose:Checking executable 'aplay'...
DEBUG:client.diagnose:Executable 'aplay' found: '/usr/bin/aplay'
DEBUG:client.diagnose:Checking executable 'espeak'...
DEBUG:client.diagnose:Executable 'espeak' found: '/usr/bin/espeak'
DEBUG:client.vocabcompiler:compiled_revision is 'bb74ae36d130ef20de710e3a77b43424b8fa774f'
DEBUG:client.brain:Looking for modules in: '/home/pi/jasper/client/modules'
DEBUG:client.brain:Found module 'Birthday' with words: ['BIRTHDAY']
DEBUG:client.brain:Found module 'Gmail' with words: ['EMAIL', 'INBOX']
DEBUG:client.brain:Found module 'HN' with words: ['HACKER', 'NEWS', 'YES', 'NO', 'FIRST', 'SECOND', 'THIRD']
DEBUG:client.brain:Found module 'Joke' with words: ['JOKE', 'KNOCK KNOCK']
DEBUG:client.brain:Found module 'Life' with words: ['MEANING', 'OF', 'LIFE']
DEBUG:client.brain:Found module 'MPDControl' with words: ['MUSIC', 'SPOTIFY']
DEBUG:client.brain:Found module 'News' with words: ['NEWS', 'YES', 'NO', 'FIRST', 'SECOND', 'THIRD']
DEBUG:client.brain:Found module 'Notifications' with words: ['FACEBOOK', 'NOTIFICATION']
DEBUG:client.brain:Found module 'Time' with words: ['TIME']
DEBUG:client.brain:Found module 'Unclear' with words: []
DEBUG:client.brain:Found module 'Weather' with words: ['WEATHER', 'TODAY', 'TOMORROW']
DEBUG:client.vocabcompiler:compiled_revision is '8c0e66f387b7177205726ecfcb3edd9df0d23653'
INFO:client.mic:Initializing PyAudio. ALSA/Jack error messages that pop up during this process are normal and can usually be safely ignored.
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
INFO:client.mic:Initialization of PyAudio completed.
DEBUG:client.tts:Saying 'How can I be of service, tony?' with 'espeak-tts'
DEBUG:client.tts:Executing espeak -v default+m3 -p 40 -s 160 -w /tmp/tmpzAqmnw.wav 'How can I be of service, tony?'
DEBUG:client.tts:Executing aplay -D hw:1,0 /tmp/tmpzAqmnw.wav
DEBUG:client.tts:Output was: 'Playing WAVE '/tmp/tmpzAqmnw.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
'
DEBUG:client.brain:Looking for modules in: '/home/pi/jasper/client/modules'
DEBUG:client.brain:Found module 'Birthday' with words: ['BIRTHDAY']
DEBUG:client.brain:Found module 'Gmail' with words: ['EMAIL', 'INBOX']
DEBUG:client.brain:Found module 'HN' with words: ['HACKER', 'NEWS', 'YES', 'NO', 'FIRST', 'SECOND', 'THIRD']
DEBUG:client.brain:Found module 'Joke' with words: ['JOKE', 'KNOCK KNOCK']
DEBUG:client.brain:Found module 'Life' with words: ['MEANING', 'OF', 'LIFE']
DEBUG:client.brain:Found module 'MPDControl' with words: ['MUSIC', 'SPOTIFY']
DEBUG:client.brain:Found module 'News' with words: ['NEWS', 'YES', 'NO', 'FIRST', 'SECOND', 'THIRD']
DEBUG:client.brain:Found module 'Notifications' with words: ['FACEBOOK', 'NOTIFICATION']
DEBUG:client.brain:Found module 'Time' with words: ['TIME']
DEBUG:client.brain:Found module 'Unclear' with words: []
DEBUG:client.brain:Found module 'Weather' with words: ['WEATHER', 'TODAY', 'TOMORROW']
INFO:apscheduler.scheduler:Scheduler started
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:No jobs; waiting until a job is added
INFO:apscheduler.scheduler:Added job "Notifier.gather" to job store "default"
INFO:client.conversation:Starting to handle conversation with keyword 'JASPER'.
DEBUG:client.conversation:Started listening for keyword 'JASPER'
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2015-01-05 23:08:23.048121+00:00 (in 29.905252 seconds)
INFO:client.stt:Transcribed: ['BUT']
DEBUG:client.conversation:Stopped listening for keyword 'JASPER'
INFO:client.conversation:Nothing has been said or transcribed.
DEBUG:client.conversation:Started listening for keyword 'JASPER'
INFO:client.stt:Transcribed: ['WITH']
DEBUG:client.conversation:Stopped listening for keyword 'JASPER'
INFO:client.conversation:Nothing has been said or transcribed.
DEBUG:client.conversation:Started listening for keyword 'JASPER'
INFO:client.stt:Transcribed: ['WITH']
DEBUG:client.conversation:Stopped listening for keyword 'JASPER'
INFO:client.conversation:Nothing has been said or transcribed.
DEBUG:client.conversation:Started listening for keyword 'JASPER'
Traceback (most recent call last):
  File "./jasper.py", line 142, in <module>
    app.run()
  File "./jasper.py", line 112, in run
    conversation.handleForever()
  File "/home/pi/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/jasper/client/mic.py", line 163, in passiveListen
    data = stream.read(CHUNK)
  File "/usr/lib/pymodules/python2.7/pyaudio.py", line 564, in read
    return pa.read_stream(self._stream, num_frames)
IOError: [Errno Input overflowed] -9981
INFO:apscheduler.scheduler:Scheduler has been shut down
Exception RuntimeError: 'Set changed size during iteration' in <bound method Mic.__del__ of <client.mic.Mic instance at 0x284c8a0>> ignored

**Comment by Holzhaus** [comment]
Probably. Can you test this and tell me if the problem persists: https://github.com/jasperproject/jasper-client/issues/240#issuecomment-68682266

**Comment by tonylu880042** [comment]
hi,
 I have same issue, but after I comment out the gmail setting the system works better although there still have other problem.
Best regards,
tony

**Comment by Holzhaus** [comment]
But no `IOError: [Errno Input overflowed] -9981` crash?

**Comment by tonylu880042** [comment]
yeap, so far it is.

**Comment by Holzhaus** [comment]
So there is some bug in the Gmail notifier. Strange.

**Comment by Saxifraga** [comment]
Has any progress been made on this issue? I am having the same problem, which persists even after commenting out my gmail address in profile.yml.
