### ISSUE TITLE
google-stt crashing Jasper

### ISSUE THREAD

**Issue by DasKatzchen** [jasperproject/jasper-client#241]
I switched my Jasper over to google-stt because I was tired of Jasper recognizing "what time is it" as "life time music" and trying to run spotify.  But it simply will not run.  The instant it hears any sound, I get this:

Traceback (most recent call last):
  File "/home/pi/jasper/client/stt.py", line 234, in transcribe
    decoded = json.loads(response_parts[-1])
  File "/usr/lib/python2.7/json/**init**.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "jasper.py", line 141, in <module>
    app.run()
  File "jasper.py", line 112, in run
    conversation.handleForever()
  File "/home/pi/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/jasper/client/mic.py", line 181, in passiveListen
    if any(PERSONA in phrase for phrase in transcribed):
TypeError: 'NoneType' object is not iterable
Exception in thread APScheduler (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 505, in run

Switching it back to Sphinx eliminates the error, so it's definitely Google-stt.

**Comment by dt-cameron** [comment]
DieKatzchen, I am having the same issue. I am so incredibly noob, how were you able to view / change you're 'outward-facing op address'? My device is able to connect to the internet otherwise, but I get the same error you did when booting jasper.

**Comment by DieterKoblenz** [comment]
Same problem here like dt-cameron.

**Comment by Holzhaus** [comment]
(https://www.whatismyip.com/)[https://www.whatismyip.com/]

Please use the [support forum](https://groups.google.com/forum/#!forum/jasper-support-forum) for these kind of issues.
