### ISSUE TITLE
NameError: global name 'cmuclmtk' is not defined

### ISSUE THREAD

**Issue by Ashish-Bansal** [jasperproject/jasper-client#281]
Hey, I was trying to run jasper client on Arch Linux and got this error. I have installed it from AUR, so all the dependencies should have been installed. I don't know what's wrong with cmuclmtk. I have installed it and its python wrapper too. I am using stt_engine: sphinx and tts_engine: espeak-tts.
I have tried google stt engine and it is working fine but I don't like its internet dependency, so that's why I want to use sphinx. 
Does anyone has an idea what's wrong with it?
```
[phantom@rig]$ jasper-voice-control
No handlers could be found for logger "client.vocabcompiler"
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/usr/share/jasper-voice-control/client/vocabcompiler.py", line 157, in compile
    self._compile_vocabulary(phrases)
  File "/usr/share/jasper-voice-control/client/vocabcompiler.py", line 263, in _compile_vocabulary
    vocabulary = self._compile_languagemodel(text, self.languagemodel_file)
  File "/usr/share/jasper-voice-control/client/vocabcompiler.py", line 284, in _compile_languagemodel
    cmuclmtk.text2vocab(text, vocab_file)
NameError: global name 'cmuclmtk' is not defined
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/usr/share/jasper-voice-control/jasper.py", line 138, in <module>
    app = Jasper()
  File "/usr/share/jasper-voice-control/jasper.py", line 101, in __init__
    stt_engine_class.get_passive_instance(),
  File "/usr/share/jasper-voice-control/client/stt.py", line 46, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/usr/share/jasper-voice-control/client/stt.py", line 38, in get_instance
    vocabulary.compile(phrases)
  File "/usr/share/jasper-voice-control/client/vocabcompiler.py", line 165, in compile
    raise e
NameError: global name 'cmuclmtk' is not defined
```

**Comment by Holzhaus** [comment]
Please run `pacman -Ql python2-cmuclmtk`.

**Comment by Ashish-Bansal** [comment]
I thought I had installed it. Huh, I missed it!
btw Thanks!!
