### ISSUE TITLE
Connection Error kills Jasper -- (-5, 'No address associated with hostname')

### ISSUE THREAD

**Issue by WilhelmWillie** [jasperproject/jasper-client#282]
Hello, I've been using Jasper for the past week or so and I'm loving it. However, I get an error every now and then that kills Jasper and the process.

I get this traceback 

```
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 146, in <module>
    app.run()
  File "/home/pi/jasper/jasper.py", line 116, in run
    conversation.handleForever()
  File "/home/pi/jasper/client/conversation.py", line 42, in handleForever
    input = self.mic.activeListenToAllOptions(threshold)
  File "/home/pi/jasper/client/mic.py", line 256, in activeListenToAllOptions
    return self.active_stt_engine.transcribe(f)
  File "/home/pi/jasper/client/stt.py", line 364, in transcribe
    r = self._get_response(data)
  File "/home/pi/jasper/client/stt.py", line 409, in _get_response
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-5, 'No address associated with hostname'))
```

every now and then when Jasper is trying to transcribe my speech. Usually my internet runs fine but every now and then there's hiccups. I'm just wondering if it would be possible to add an 'except ConnectionError' that will ignore or deal with these errors when they pop up without terminating the Jasper process. 

I should note that I'm using the AT&T STT engine although I don't think it's a problem with the engine

**Comment by Holzhaus** [comment]
In fact, it is a problem with the engine. The AT&T engine needs a persistant internet connection. If you connection fails now and then, try the [Pocketsphinx STT engine](http://jasperproject.github.io/documentation/configuration/#pocketsphinx-stt).
