### ISSUE TITLE
Failed to initialize PocketSphinx

### ISSUE THREAD

**Issue by Ashish-Bansal** [jasperproject/jasper-client#283]
I am getting following error. I have checked old issues and some have this type of problem.
I have tried deleting .jasper/vocabularies. I am trying to run it on Arch Linux. 
Any solution to this??

```
$ jasper-voice-control --debug
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
DEBUG:client.diagnose:Checking network connection to server 'www.google.com'...
DEBUG:client.diagnose:Network connection working
DEBUG:__main__:Trying to read config file: '/home/phantom/.jasper/profile.yml'
DEBUG:client.diagnose:Checking python import 'pocketsphinx'...
DEBUG:client.diagnose:Python module 'pocketsphinx' found: '/usr/lib/python2.7/site-packages/pocketsphinx.so'
DEBUG:client.diagnose:Checking executable 'aplay'...
DEBUG:client.diagnose:Executable 'aplay' found: '/usr/bin/aplay'
DEBUG:client.diagnose:Checking executable 'espeak'...
DEBUG:client.diagnose:Executable 'espeak' found: '/usr/bin/espeak'
DEBUG:client.vocabcompiler:compiled_revision is 'bb74ae36d130ef20de710e3a77b43424b8fa774f'
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/usr/share/jasper-voice-control/jasper.py", line 138, in <module>
    app = Jasper()
  File "/usr/share/jasper-voice-control/jasper.py", line 101, in __init__
    stt_engine_class.get_passive_instance(),
  File "/usr/share/jasper-voice-control/client/stt.py", line 46, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/usr/share/jasper-voice-control/client/stt.py", line 40, in get_instance
    instance = cls(**config)
  File "/usr/share/jasper-voice-control/client/stt.py", line 95, in __init__
    **vocabulary.decoder_kwargs)
  File "pocketsphinx.pyx", line 476, in pocketsphinx.Decoder.__init__ (pocketsphinx.c:3959)
RuntimeError: Failed to initialize PocketSphinx
```

Detailed output of jasper/client/start.sh : http://pastebin.com/qGQx4ss3
Someone is also having exactly same problem and has asked it on google groups : https://groups.google.com/forum/#!topic/jasper-support-forum/09NXYvyrODc

**Comment by Holzhaus** [comment]
I assume your `hmm_dir` is wrong. Please configure it correctly (find out how to do this [here](http://jasperproject.github.io/documentation/configuration/#pocketsphinx-stt)).

On ArchLinux, you can run `cat /var/lib/jasper/.jasper/profile.yml` to get the correct path.
