### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'upper'

### ISSUE THREAD

**Issue by makeacoffeeprj** [jasperproject/jasper-client#327]
Hi everyone! I just made a fresh installation of jasper client and I get this error after few seconds I started jasper:
```
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 148, in <module>
    app.run()
  File "/home/pi/jasper/jasper.py", line 118, in run
    conversation.handleForever()
  File "/home/pi/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/jasper/client/mic.py", line 179, in passiveListen
    transcribed = self.passive_stt_engine.transcribe(f)
  File "/home/pi/jasper/client/stt.py", line 613, in transcribe
    transcribed = [text.upper()]
AttributeError: 'NoneType' object has no attribute 'upper'
```

How can I fix this issue? This is my profile.yml:

carrier: sms.vodafone.it
first_name: Diego
gmail_address: diego.etc@gmail.com
gmail_password: etc
last_name: Braga
location: Milano
phone_number: '33333333333333'
prefers_email: true
stt_engine: witai
witai-stt:
  access_token:    W666666666666
tts_engine: espeak-tts
timezone: Europe/Rome

**Comment by Holzhaus** [comment]
Looks like a bug in the Wit.ai STT engine. I'll see if I can fix that tomorrow.
