### ISSUE TITLE
ERROR:client.g2p:ERROR:client.vocabcompiler:Fatal compilation Error occured,

### ISSUE THREAD

**Issue by daehgib** [jasperproject/jasper-client#336]
What's wrong with this? Can somebody help me

*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:Network not connected. This may prevent Jasper from running properl                                                                                        y.
ERROR:client.g2p:Command 'phonetisaurus-g2p --model=/home/pi/phonetisaurus/g014b                                                                                        2b.fst --input=/tmp/tmpNP6Dcc.g2p --words --isfile' return with exit status -4
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 271, in _compile_vocabula                                                                                        ry
    self._compile_dictionary(vocabulary, self.dictionary_file)
  File "/home/pi/jasper/client/vocabcompiler.py", line 321, in _compile_dictiona                                                                                        ry
    phonemes = g2pconverter.translate(words)
  File "/home/pi/jasper/client/g2p.py", line 130, in translate
    output = self._translate_words(words)
  File "/home/pi/jasper/client/g2p.py", line 119, in _translate_words
    nbest=self.nbest)
  File "/home/pi/jasper/client/g2p.py", line 56, in execute
    raise OSError("Command execution failed")
OSError: Command execution failed
ERROR:root:Error occured!
Traceback (most recent call last):
  File "./jasper/jasper.py", line 143, in <module>
    app = Jasper()
  File "./jasper/jasper.py", line 106, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
OSError: Command execution failed

**Comment by shajmaan** [comment]
how did u solve it?
am stuck at the same place

**Comment by WirelessMind** [comment]
same error.
Any solution?

**Comment by bwaaaaaa** [comment]
having the same issue, please don;t tell me to reinstall everything again :(

**Comment by DarthToker** [comment]
Try this site. 
http://www.speech.cs.cmu.edu/tools/lmtool-new.html

Carl Dirzuweit
