### ISSUE TITLE
jasper.py crashes after changing module (SOLVED)

### ISSUE THREAD

**Issue by professorDODO** [jasperproject/jasper-client#338]
I finally got jasper working on my Pi 2 B and wanted to start creating new modules. So I created a new one, which simply response "hello" after saying the hot word again. That worked totally fine, but after changing some things I sadly can't remember, changing any modules let Jasper crash with the followed Debug log. After undoing all the changes in the modules, Jasper crashes with the same error message. After booting from a backup Jasper works and the bug is recreatable.

EDIT: The Bug also occurs when I just deleted the newly created module. Also when I create the error, delete the whole Jasper dir and copy it from a backup, where Jasper worked, the bug stays the same.

SOLVED:
just simply added this to `profile.yml`
`pocketsphinx:`
`  fst_model: '../phonetisaurus/g014b2b.fst'                              #optional`
`  hmm_dir: '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' #optional`

And here is the log, running in debug mode:
```shell
pi@oraclepi ~/jasper $ python jasper.py --debug`
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
DEBUG:client.diagnose:Checking network connection to server 'www.google.com'...
DEBUG:client.diagnose:Network connection working
DEBUG:__main__:Trying to read config file: '/home/pi/.jasper/profile.yml'
DEBUG:client.diagnose:Checking python import 'pocketsphinx'...
DEBUG:client.diagnose:Python module 'pocketsphinx' found: '/usr/local/lib/python2.7/dist-packages/pocketsphinx.so'
DEBUG:client.diagnose:Checking executable 'aplay'...
DEBUG:client.diagnose:Executable 'aplay' found: '/usr/bin/aplay'
DEBUG:client.diagnose:Checking python import 'mad'...
DEBUG:client.diagnose:Python module 'mad' found: '/usr/lib/pymodules/python2.7/madmodule.so'
DEBUG:client.diagnose:Checking python import 'gtts'...
DEBUG:client.diagnose:Python package 'gtts' found: '/usr/local/lib/python2.7/dist-packages/gtts/__init__.py'
DEBUG:client.diagnose:Checking network connection to server 'www.google.com'...
DEBUG:client.diagnose:Network connection working
DEBUG:client.vocabcompiler:compiled_revision is '0b5226c70da9e47b6af7cdf5eb1919aa0b8d40fc'
DEBUG:client.brain:Looking for modules in: '/home/pi/jasper/client/modules'
DEBUG:client.brain:Found module 'Birthday' with words: ['BIRTHDAY']
DEBUG:client.brain:Found module 'Gmail' with words: ['EMAIL', 'INBOX']
DEBUG:client.brain:Found module 'HN' with words: ['HACKER', 'NEWS', 'YES', 'NO', 'FIRST', 'SECOND', 'THIRD']
DEBUG:client.brain:Found module 'Joke' with words: ['JOKE', 'KNOCK KNOCK']
DEBUG:client.brain:Found module 'Life' with words: ['MEANING', 'OF', 'LIFE']
DEBUG:client.brain:Found module 'MPDControl' with words: ['MUSIC', 'SPOTIFY']
DEBUG:client.brain:Found module 'News' with words: ['NEWS', 'YES', 'NO', 'FIRST', 'SECOND', 'THIRD']
DEBUG:client.brain:Found module 'Notifications' with words: ['FACEBOOK', 'NOTIFICATION']
DEBUG:client.brain:Found module 'Time' with words: ['TIME']
DEBUG:client.brain:Found module 'Unclear' with words: []
DEBUG:client.brain:Found module 'Weather' with words: ['WEATHER', 'TODAY', 'TOMORROW']
INFO:client.vocabcompiler:Starting compilation...
DEBUG:client.vocabcompiler:Compiling languagemodel...
DEBUG:client.vocabcompiler:Creating vocab file: '/tmp/tmp6s1HBe.vocab'
DEBUG:cmuclmtk:text2wfreq : Reading text from standard input...
DEBUG:cmuclmtk:text2wfreq : Done.
DEBUG:cmuclmtk:Command 'text2wfreq -hash 1000000 -verbosity 2' returned with exit code '0'.
DEBUG:cmuclmtk:wfreq2vocab : Will generate a vocabulary containing the most
DEBUG:cmuclmtk:frequent 20000 words. Reading wfreq stream from stdin...
DEBUG:cmuclmtk:wfreq2vocab : Done.
DEBUG:cmuclmtk:Command 'wfreq2vocab -verbosity 2 -records 1000000' returned with exit code '0'.
DEBUG:client.vocabcompiler:Creating languagemodel file: '/home/pi/.jasper/vocabularies/pocketsphinx-vocabulary/default/languagemodel'
DEBUG:cmuclmtk:text2idngram
DEBUG:cmuclmtk:Vocab                  : /tmp/tmp6s1HBe.vocab
DEBUG:cmuclmtk:Output idngram         : /tmp/tmpEVGp6D.idngram
DEBUG:cmuclmtk:N-gram buffer size     : 100
DEBUG:cmuclmtk:Hash table size        : 2000000
DEBUG:cmuclmtk:Temp directory         : cmuclmtk-9u3mgz
DEBUG:cmuclmtk:Max open files         : 20
DEBUG:cmuclmtk:FOF size               : 10
DEBUG:cmuclmtk:n                      : 3
DEBUG:cmuclmtk:Initialising hash table...
DEBUG:cmuclmtk:Reading vocabulary...
DEBUG:cmuclmtk:Allocating memory for the n-gram buffer...
DEBUG:cmuclmtk:Reading text into the n-gram buffer...
DEBUG:cmuclmtk:20,000 n-grams processed for each ".", 1,000,000 for each line.
DEBUG:cmuclmtk:Sorting n-grams...
DEBUG:cmuclmtk:Writing sorted n-grams to temporary file cmuclmtk-9u3mgz/1
DEBUG:cmuclmtk:Merging 1 temporary files...
DEBUG:cmuclmtk:2-grams occurring:	N times		> N times	Sug. -spec_num value
DEBUG:cmuclmtk:0						     46		     56
DEBUG:cmuclmtk:1				     45		      1		     11
DEBUG:cmuclmtk:2				      0		      1		     11
DEBUG:cmuclmtk:3				      0		      1		     11
DEBUG:cmuclmtk:4				      0		      1		     11
DEBUG:cmuclmtk:5				      0		      1		     11
DEBUG:cmuclmtk:6				      0		      1		     11
DEBUG:cmuclmtk:7				      0		      1		     11
DEBUG:cmuclmtk:8				      0		      1		     11
DEBUG:cmuclmtk:9				      0		      1		     11
DEBUG:cmuclmtk:10				      0		      1		     11
DEBUG:cmuclmtk:3-grams occurring:	N times		> N times	Sug. -spec_num value
DEBUG:cmuclmtk:0						     67		     77
DEBUG:cmuclmtk:1				     67		      0		     10
DEBUG:cmuclmtk:2				      0		      0		     10
DEBUG:cmuclmtk:3				      0		      0		     10
DEBUG:cmuclmtk:4				      0		      0		     10
DEBUG:cmuclmtk:5				      0		      0		     10
DEBUG:cmuclmtk:6				      0		      0		     10
DEBUG:cmuclmtk:7				      0		      0		     10
DEBUG:cmuclmtk:8				      0		      0		     10
DEBUG:cmuclmtk:9				      0		      0		     10
DEBUG:cmuclmtk:10				      0		      0		     10
DEBUG:cmuclmtk:text2idngram : Done.
DEBUG:cmuclmtk:Command 'text2idngram -vocab /tmp/tmp6s1HBe.vocab -idngram /tmp/tmpEVGp6D.idngram -buffer 100 -hash 2000000 -files 20 -verbosity 2 -n 3 -fof_size 10' returned with exit code '0'.
DEBUG:cmuclmtk:Warning : OOV fraction specified, but will not be used, since vocab type is not 2.
DEBUG:cmuclmtk:n : 3
DEBUG:cmuclmtk:Input file : /tmp/tmpEVGp6D.idngram     (binary format)
DEBUG:cmuclmtk:Output files :
DEBUG:cmuclmtk:ARPA format   : /home/pi/.jasper/vocabularies/pocketsphinx-vocabulary/default/languagemodel
DEBUG:cmuclmtk:Vocabulary file : /tmp/tmp6s1HBe.vocab
DEBUG:cmuclmtk:Cutoffs :
DEBUG:cmuclmtk:2-gram : 0     3-gram : 0
DEBUG:cmuclmtk:Vocabulary type : Open - type 1
DEBUG:cmuclmtk:Minimum unigram count : 0
DEBUG:cmuclmtk:Zeroton fraction : 1
DEBUG:cmuclmtk:Counts will be stored in two bytes.
DEBUG:cmuclmtk:Count table size : 65535
DEBUG:cmuclmtk:Discounting method : Good-Turing
DEBUG:cmuclmtk:Discounting ranges :
DEBUG:cmuclmtk:1-gram : 1     2-gram : 7     3-gram : 7
DEBUG:cmuclmtk:Memory allocation for tree structure :
DEBUG:cmuclmtk:Allocate 100 MB of memory, shared equally between all n-gram tables.
DEBUG:cmuclmtk:Back-off weight storage :
DEBUG:cmuclmtk:Back-off weights will be stored in four bytes.
DEBUG:cmuclmtk:Reading vocabulary.
DEBUG:cmuclmtk:read_wlist_into_siht: a list of 25 words was read from "/tmp/tmp6s1HBe.vocab".
DEBUG:cmuclmtk:read_wlist_into_array: a list of 25 words was read from "/tmp/tmp6s1HBe.vocab".
DEBUG:cmuclmtk:WARNING: <s> appears as a vocabulary item, but is not labelled as a
DEBUG:cmuclmtk:context cue.
DEBUG:cmuclmtk:Allocated space for 3571428 2-grams.
DEBUG:cmuclmtk:Allocated space for 8333333 3-grams.
DEBUG:cmuclmtk:table_size 26
DEBUG:cmuclmtk:Allocated 57142848 bytes to table for 2-grams.
DEBUG:cmuclmtk:Allocated (2+33333332) bytes to table for 3-grams.
DEBUG:cmuclmtk:Processing id n-gram file.
DEBUG:cmuclmtk:20,000 n-grams processed for each ".", 1,000,000 for each line.
DEBUG:cmuclmtk:Calculating discounted counts.
DEBUG:cmuclmtk:Warning : 1-gram : Discounting range is 1; setting P(zeroton)=P(singleton).
DEBUG:cmuclmtk:Discounted value : 0.91
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 6.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 5.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 4.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 3.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 2.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 1.
DEBUG:cmuclmtk:Warning : 2-gram : Discounting range of 1 is equivalent to excluding
DEBUG:cmuclmtk:singletons.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 0.
DEBUG:cmuclmtk:Warning : 2-gram : Discounting is disabled.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 6.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 5.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 4.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 3.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 2.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 1.
DEBUG:cmuclmtk:Warning : 3-gram : Discounting range of 1 is equivalent to excluding
DEBUG:cmuclmtk:singletons.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 0.
DEBUG:cmuclmtk:Warning : 3-gram : Discounting is disabled.
DEBUG:cmuclmtk:Unigrams's discount mass is 0.027255 (n1/N = 0.313433)
DEBUG:cmuclmtk:2 zerotons, P(zeroton) = 0.0136275 P(singleton) = 0.0136275
DEBUG:cmuclmtk:prob[UNK] = 0.0136275
DEBUG:cmuclmtk:Incrementing contexts...
DEBUG:cmuclmtk:Calculating back-off weights...
DEBUG:cmuclmtk:Writing out language model...
DEBUG:cmuclmtk:ARPA-style 3-gram will be written to /home/pi/.jasper/vocabularies/pocketsphinx-vocabulary/default/languagemodel
DEBUG:cmuclmtk:idngram2lm : Done.
DEBUG:cmuclmtk:Command 'idngram2lm -idngram /tmp/tmpEVGp6D.idngram -vocab /tmp/tmp6s1HBe.vocab -vocab_type 1 -oov_fraction 0.5 -min_unicount 0 -verbosity 2 -n 3 -arpa /home/pi/.jasper/vocabularies/pocketsphinx-vocabulary/default/languagemodel -bin_input' returned with exit code '0'.
DEBUG:client.vocabcompiler:Getting words from vocab file and removing it afterwards...
DEBUG:client.vocabcompiler:Starting dictionary...
DEBUG:client.vocabcompiler:Getting phonemes for 23 words...
DEBUG:client.diagnose:Checking executable 'phonetisaurus-g2p'...
DEBUG:client.diagnose:Executable 'phonetisaurus-g2p' found: '/usr/local/bin/phonetisaurus-g2p'
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 271, in _compile_vocabulary
    self._compile_dictionary(vocabulary, self.dictionary_file)
  File "/home/pi/jasper/client/vocabcompiler.py", line 320, in _compile_dictionary
    g2pconverter = PhonetisaurusG2P(**PhonetisaurusG2P.get_config())
  File "/home/pi/jasper/client/g2p.py", line 93, in __new__
    "instance.") % fst_model)
OSError: FST model ''/home/pi/jasper/../phonetisaurus/g014b2b.fst'' does not exist! Can't create instance.
ERROR:root:Error occured!
Traceback (most recent call last):
  File "jasper.py", line 143, in <module>
    app = Jasper()
  File "jasper.py", line 107, in __init__
    stt_engine_class.get_active_instance())
  File "/home/pi/jasper/client/stt.py", line 53, in get_active_instance
    return cls.get_instance('default', phrases)
  File "/home/pi/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
OSError: FST model ''/home/pi/jasper/../phonetisaurus/g014b2b.fst'' does not exist! Can't create instance.

**Comment by Holzhaus** [comment]
Great, i'll close this.

**Comment by dhanmoh123** [comment]
How did you solve this problem? Can you please tell me in detail?
