### ISSUE TITLE
jaser on ubuntu jaser on rpi B+

### ISSUE THREAD

**Issue by twinspica14** [jasperproject/jasper-client#345]
first we tried on rpi
it all seemed to work fine but the problem we were facing was mic,we couldnt configure mic to work with rasberry and soon whole system crashed...so i thought lets give a try on ubuntu
now the problem is lot errors,plz anyone just look at it and help

WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "../client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "../client/vocabcompiler.py", line 269, in _compile_vocabulary
    vocabulary = self._compile_languagemodel(text, self.languagemodel_file)
  File "../client/vocabcompiler.py", line 290, in _compile_languagemodel
    cmuclmtk.text2vocab(text, vocab_file)
  File "/usr/local/lib/python2.7/dist-packages/cmuclmtk/__init__.py", line 485, in text2vocab
    text2wfreq(text, wfreq_file, **text2wfreq_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cmuclmtk/__init__.py", line 114, in text2wfreq
    raise ConversionError("'%s' returned with non-zero exit status '%s'" % (cmd[0], exitcode))
ConversionError: 'text2wfreq' returned with non-zero exit status '127'
ERROR:root:Error occured!
Traceback (most recent call last):
  File "../jasper.py", line 143, in <module>
    app = Jasper()
  File "../jasper.py", line 106, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "../client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "../client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "../client/vocabcompiler.py", line 171, in compile
    raise e

on rasberry
the problem was with mic

**Comment by twinspica14** [comment]
latest error
            JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:root:Error occured!
Traceback (most recent call last):
  File "../jasper.py", line 143, in <module>
    app = Jasper()
  File "../jasper.py", line 88, in __init__
    stt_engine_class = stt.get_engine_by_slug(stt_engine_slug)
  File "../client/stt.py", line 639, in get_engine_by_slug
    raise ValueError("No STT engine found for slug '%s'" % slug)
ValueError: No STT engine found for slug 'sphinx fst_model:'/home/nil/phonetisaurus/g014b2b.fst' hmm_dir:'/home/nil/Desktop/sphinx/pocketsphinx-0.8/model/hmm/en_US/hub4$'

**Comment by twinspica14** [comment]
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
WARNING:client.brain:Skipped module 'MPDControl' due to an error.
Traceback (most recent call last):
  File "../client/brain.py", line 43, in get_modules
    mod = loader.load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/nil/jasper/client/modules/MPDControl.py", line 6, in <module>
    from client.mic import Mic
  File "../client/mic.py", line 9, in <module>
    import pyaudio
ImportError: No module named pyaudio
JASPER: How can I be of service, max?
WARNING:client.brain:Skipped module 'MPDControl' due to an error.
Traceback (most recent call last):
  File "../client/brain.py", line 43, in get_modules
    mod = loader.load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/nil/jasper/client/modules/MPDControl.py", line 6, in <module>
    from client.mic import Mic
  File "../client/mic.py", line 9, in <module>
    import pyaudio
ImportError: No module named pyaudio
WARNING:client.notifier:gmail_address or gmail_password not set in profile, Gmail notifier will not be used
YOU: hi
JASPER: I'm sorry, could you repeat that?
YOU: can u talk
JASPER: I beg your pardon?
YOU: talk
JASPER: I'm sorry, could you repeat that?
YOU: can u run python
JASPER: I beg your pardon?
YOU: joke
JASPER: Knock knock
YOU: who is there
JASPER: doris
YOU: doris who
JASPER: door is locked... that's why I'm knocking, you idiot
YOU: lol
JASPER: My apologies, could you try saying that again?
YOU: dont mind
JASPER: My apologies, could you try saying that again?
YOU: u suck
JASPER: Say that again?
YOU: 


how should i make it to speak and listen to me

**Comment by twinspica14** [comment]
now it worked
leaving   
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

**Comment by twinspica14** [comment]
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['IT IT']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['SAY']
INFO:client.stt:Transcribed: ['BE']
No disturbance detected
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['DID SAY']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['IN WITH']
INFO:client.stt:Transcribed: ['IN']
INFO:client.stt:Transcribed: ['JASPER']
INFO:client.stt:Transcribed: ['NO YES NEWS TIME TIME']
INFO:client.stt:Transcribed: ['TIME']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['BEING ON']
INFO:client.stt:Transcribed: ['DID IT BEING']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['IN SAY IT']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['IT']
INFO:client.stt:Transcribed: ['NOW IN']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['IN']
INFO:client.stt:Transcribed: ['JASPER']
INFO:client.stt:Transcribed: ['TODAY NEWS TODAY']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['IS BEING']
INFO:client.stt:Transcribed: ['']


still no outut yet

**Comment by twinspica14** [comment]
now i am getting beep response and nothingelse

**Comment by twinspica14** [comment]
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started






any help ,its been almost a week... still no sound

**Comment by twinspica14** [comment]
@jasperproject  @shbhrsaha  @Holzhaus  @crm416  guys just give a hint, i tried on B B+ UBUNTU 14.04
all get to same step

INFO:client.stt:Transcribed: ['NOW IN']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['IN']
INFO:client.stt:Transcribed: ['JASPER']
INFO:client.stt:Transcribed: ['TODAY NEWS TODAY']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['IS BEING']
INFO:client.stt:Transcribed: ['']

still no outut yet

**Comment by twinspica14** [comment]
i just ran debug on jasper.py
errors
aplay:set params:1087:channel count not available

errror: client.brain.failed to execute

brain.py line 73
news.py 116
mic.py 262
tts.py 172

**Comment by twinspica14** [comment]
ok so it was easy just took almost 3 weeks to realise what changes had to be made in program files,but finally it runs on ubuntu ,rpi b,rpi b+....

**Comment by twinspica14** [comment]
u can close this .....
