### ISSUE TITLE
Channels not specified with new "Quickstart" install

### ISSUE THREAD

**Issue by Hadjimina** [jasperproject/jasper-client#358]
Heyo guys

So I am currently unable to start Jasper becase of this error :

    Traceback (most recent call last):
      File "/home/pi/jasper/jasper.py", line 148, in <module>
        app.run()
      File "/home/pi/jasper/jasper.py", line 115, in run
       self.mic.say(salutation)
      File "/home/pi/jasper/client/mic.py", line 262, in say
        self.speaker.say(phrase)
      File "/home/pi/jasper/client/tts.py", line 472, in say
        self.play_mp3(tmpfile)
      File "/home/pi/jasper/client/tts.py", line 100, in play_mp3
        wav.setframerate(mf.samplerate())
      File "/usr/lib/python2.7/wave.py", line 358, in setframerate
       raise Error, 'bad frame rate'
    wave.Error: bad frame rate
    Exception wave.Error: Error('# channels not specified',) in <bound method Wave_write.__del__ of 
    <wave.Wave_write instance at 0xfdc2b0>> ignored

aplay and arecord both show my sound devices (jack audio & usb mic) and both are working (tried them with recording something with arecord and playback with aplay).

Can anyone help me ? 

Thx for your responses

**Comment by Hadjimina** [comment]
Fixed it with changing tts from google to ivona
