### ISSUE TITLE
ALSA not set up the same in Rasp Pi 2 Jesse?

### ISSUE THREAD

**Issue by mathias** [jasperproject/jasper-client#388]
Hi all,

I failed to get the Jasper image to boot on my Raspberry Pi 2, so I went back to a clean install of Raspbian Jesse and tried to install everything. I think I have enough installed and configured that it should boot, but I'm getting this:

```
[.. jasper normal booting ...]
jack server is not running or cannot be started
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' f$iled in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &out$utLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
  File "./jasper.py", line 148, in <module>
    app.run()
  File "./jasper.py", line 118, in run
    conversation.handleForever()
  File "/home/pi/dev/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/dev/jasper/client/mic.py", line 110, in passiveListen
    frames_per_buffer=CHUNK)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 747, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 442, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno Invalid sample rate] -9997
```

 I feel like I've got the ALSA stuff set up right, even though the instructions point at files that don't exist anymore. I was able to get things set up so that:

```
$ cat /proc/asound/cards
 0 [Device         ]: USB-Audio - USB PnP Sound Device
                      C-Media Electronics Inc. USB PnP Sound Device at usb-3f980000.usb-1.5, full spe
 1 [ALSA           ]: bcm2835 - bcm2835 ALSA
                      bcm2835 ALSA
```

But as mentioned elsewhere, the `/etc/modprobe.d/alsa-base.conf` and other files pointed to by the instructions don't exist on Jesse.

Has anyone got this working on a Pi 2?

**Comment by marmil** [comment]
Hi,
after struggeling for weeks i managed to get it working for my Pi 2 under latest Jessie.

See here:
https://groups.google.com/forum/#!topic/jasper-support-forum/DzsFdAKYbEo

I recognized that you have to take care that the /etc/asound.conf file and the ~/.asoundrc files are not existing ( in my case with the given link it does not work then).

If you and others wish , i can make a 16GB image from my version.

**Comment by mathias** [comment]
It seems like Jasper might need a local config file (for jasper-client, not just depending on the alsa config) for configuring sound hardware. I imagine that if you try to use this outside of a Rasp Pi, the devices could be very different. Being able to specify which devices to use in a Jasper config would make more sense.

**Comment by Holzhaus** [comment]
@mathias This does already work in the current development version of jasper. Check out the `jasper-dev` branch, not only supports configuring audio devices, but also 2 different audio engines (PyAudio and ALSA).

**Comment by mathias** [comment]
Thanks! I'll give the branch a try. Is there any different documentation or pointers about how to set up the STT and TTS engines on Jesse? 

A quick search in aptitude tells me that `pocketsphinx` is available but its dependencies are not. I might try to train Julius though, if I have the power of the RaspPi 2 to run on.

`flite` appears to be available but `libttspico-utils` is not (for SVOX Pico TTS) -- I guess I'll stick with flite.

**Comment by housni** [comment]
@mathias, `libttspico-utils` is available via the source `deb http://ftp.de.debian.org/debian jessie main non-free`. Of course, you'd replace the appropriate mirror prefix based on your location.

I found that information here: https://packages.debian.org/jessie/all/libttspico-data/download

I had some trouble getting the USB device to be the default. Any pointers would be appreciated.

I'm almost done with a Chef recipe that installs everything, compiles it all and sets it all up, I just need to figure out setting the default USB device and then I can share it via Github.
