### ISSUE TITLE
ImportError: cannot import name NewConnectionError

### ISSUE THREAD

**Issue by lordzweigar** [jasperproject/jasper-client#400]
I am running Manjaro Linux, and I have tried both the AUR Repo and building from scratch.
I get the same error regardless:

─── ./jasper/jasper.py 
Traceback (most recent call last):
  File "./jasper/jasper.py", line 12, in <module>
    from client import tts, stt, jasperpath, diagnose
  File "/home/anon/.jasper/jasper/client/tts.py", line 20, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 60, in <module>
    from .api import request, get, head, post, patch, put, delete, options
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 14, in <module>
    from . import sessions
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 27, in <module>
    from .adapters import HTTPAdapter
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 27, in <module>
    from .packages.urllib3.exceptions import NewConnectionError
ImportError: cannot import name NewConnectionError
──! 

This is my profile.yml:

carrier: ''
first_name: anon
gmail_password: ''
last_name: anon
phone_number: ''
prefers_email: true
stt_engine: julius
julius:
 hmmdefs: 'julius/hmmdefs'
 tiedlist: 'julius/tiedlist'
 lexicon:  'VoxForge.tgz'
 lexicon_archive_member: 'VoxForge/VoxForgeDict'

tts_engine: espeak-tts

_the folder julius is inside of .jasper and contains Julius_AcousticModels_8kHz-16bit_MFCC_O_D_(0.9.0)

_NOTE: yaourt -S jasper-stt-pocketsphinx is currently broken due to an non-existant google-code repo. For that reason I am using Julius, to no avail._

and yes, requests is installed. as is urllib3 (installed with both pip2 and pip)

**Comment by lordzweigar** [comment]
pip being pip and not actually updating packages ...
