### ISSUE TITLE
Jasper wan't start

### ISSUE THREAD

**Issue by DefaltTo** [jasperproject/jasper-client#418]
Hello everybody.
I am trying to make Jasper running on a Raspberry Pi model B+
I tried to used PocketSphinx as a STT but every time i tried to make phonetisaurus the process stop and no phonetisaurus-g2p wasn't made.
Now i'm trying to use wit.ai but every time I lunch Jasper this apear:
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:root:Error occured!
Traceback (most recent call last):
  File "jasper.py", line 143, in <module>
    app = Jasper()
  File "jasper.py", line 106, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/jasper/client/stt.py", line 42, in get_instance
    instance = cls(**config)
TypeError: __init__() takes exactly 2 arguments (1 given)

Can someone give me assistance?
I want to use Jasper as a voice control over my house but I am stuck here.
P.S. I have already edit profile.yml with the wit.ai and espeak lines.

**Comment by Holzhaus** [comment]
You probaböy forgot the Wit.ai Access token.

**Comment by DefaltTo** [comment]
I have insert it on the profile.yml with the "notepad" like this:

*other things 
stt_engine: witai
witai-stt:
  access_token: *access token code

Did I edit it in the wrong way?

**Comment by Holzhaus** [comment]
You need to indent `access_token:` (with spaces).

**Comment by DefaltTo** [comment]
I am not so good in Python now, can you make me an example ?

**Comment by Holzhaus** [comment]
```yaml
stt_engine: witai
witai-stt:
    access_token: YOURACCESSTOKEN
```

**Comment by DefaltTo** [comment]
Nothing.... still get the same error.... even the access token is correct but, it keep not working

**Comment by Anotherthoughtkrime** [comment]
man im in the same boat

**Comment by mattcurrycom** [comment]
What branch are you on?  Also, how many spaces there?  And are you using the server token?
I have examples on my site that work if you just want to copy/paste ur key in.
http://www.mattcurry.com/projects-2/the-jasper-project/jasper-project-useful-links/
There are 'profile examples' there if you want to try those.  I have seen this before.  Also, make sure you stop the daemon if you are using my image.  Then try running it manually ```python jasper.py --debug```

**Comment by mattcurrycom** [comment]
Please go ahead and close this, as it is actually not an issue with the code.  Join me either in our forums or slack room and I am happy to help.  We also have quite a few members in there that can help as well if I am not there.

https://groups.google.com/forum/#!forum/jasper-support-forum

**Comment by wullu** [comment]
hello friends, pls be aware of mattcurrycom. first he will ask you to join jasper forum and once you go there and start asking questions, he will force you to join slack channel. but if you refused to join slack channel and ask more questions...... dang.... blocked..... banned.....from jasper support forum.
he will delete your messages from forum if he dont like it or dont have answer for it.
i dont know his history but i think he has some mental problem!!!

**Comment by mattcurrycom** [comment]
I don't force anyone to join anything.  I only remove banned authors posts if they are hateful or hostile towards the community.  I warned you 3 times, and you were removed.

**Comment by mattcurrycom** [comment]
Also @wullu appears to be a duplicate account of another user we have an issue with previously...

Oct 8, 2016 - Creation Date...

I don't have time for such things.  I have blocked the user here from my account.
