### ISSUE TITLE
Jasper not working

### ISSUE THREAD

**Issue by tommoholmes10** [jasperproject/jasper-client#438]
I have installed julius and espeak
when I running jasper I get
```
Traceback (most recent call last):
  File "jasper.py", line 12, in <module>
    from client import tts, stt, jasperpath, diagnose
  File "/home/tomo/jasper/client/tts.py", line 41, in <module>
    import diagnose
  File "/home/tomo/jasper/client/diagnose.py", line 9, in <module>
    import pip.req
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
```

**Comment by Holzhaus** [comment]
http://stackoverflow.com/a/27425458
