### ISSUE TITLE
swift tts i purchased but swift doesnt allow to record it only works from command line

### ISSUE THREAD

**Issue by affordablewindurbines** [jasperproject/jasper-client#441]
i got ripped off by cepstral i called about tech support the guy was an @@@ THEN SAYS DONT CALL  THEM  AGAIN DONT WORRY ABOUT CEPSTRAL SUPPORT SUCKS THEY ARE RUDE DONT WANT TO HELP A PAYING CUSTOMER , IT IS OVERPRICED ANYWAY AND IT IS 35 DOLLARS TO TALK TO AN @@@ @@@@!
swift tts i purchased it but swift doesn’t allow to record it only works from terminal command i.e : aoss swift hello world  or  padsp swift hello world for example it doesn’t allow for recording then playback im wondering why doesn’t the tts just goe directly to the tts engine for tts ? Instead of having to make a recording then play it back with for example aplay ? im using larence tts from cepstral and im running jasper on a linux mint machine , any help or advice would be nice thanks

**Comment by affordablewindurbines** [comment]
also the speed is way to fast with any of the tts engines when ive changed them should it be like the settings for espeak in tts.py ? 160 words a minute?

**Comment by affordablewindurbines** [comment]
ERROR:root:Error occured!
Traceback (most recent call last):
  File "jasper.py", line 153, in <module>
    app = Jasper()
  File "jasper.py", line 102, in __init__
    tts_engine_class = tts.get_engine_by_slug(tts_engine_slug)
  File "/home/john/jasper/client/tts.py", line 657, in get_engine_by_slug
    raise ValueError("No TTS engine found for slug '%s'" % slug)
ValueError: No TTS engine found for slug 'swift-tts'

**Comment by affordablewindurbines** [comment]
so could i put this in the tts module some how? 
Try the subprocess module:

import subprocess
subprocess.call(['swift', "text to be spoken"])

to read a file:

subprocess.call(['swift', '-f', 'filename.wav'])

**Comment by affordablewindurbines** [comment]
WARNING:client.tts:Neither voice nor voice_dir set!
Traceback (most recent call last):
  File "jasper.py", line 158, in <module>
    app.run()
  File "jasper.py", line 127, in run
    passiveEnabled)
TypeError: __init__() takes exactly 4 arguments (5 given)

**Comment by affordablewindurbines** [comment]
well this is supposed to run from python but ? 

Try the subprocess module:

import subprocess
subprocess.call(['swift', "text to be spoken"])

to read a file:

subprocess.call(['swift', '-f', 'filename.wav'])

**Comment by affordablewindurbines** [comment]
and i am also working on a gui for this and trying to add a i function learning with pybrain but the espeak voices suck! im tied of hearing a droid thats hard to understand

**Comment by affordablewindurbines** [comment]
i got ripped off by cepstral i called about tech support the guy was an @@@ THEN SAYS DONT CALL  THEM  AGAIN DONT WORRY ABOUT CEPSTRAL SUPPORT IT SUCKS ANYWAY AND IT IS 35 DOLLARS TO TALK TO AN @@@ @@@@!

**Comment by affordablewindurbines** [comment]
i changed the espeak settings to make the voice sound better in client/tts.py  it sounds alot better 
especially on small usb speakers someone may find this helpfull

SLUG = "espeak-tts"

    def __init__(self, voice='default+m7', pitch_adjustment=60,
                 words_per_minute=170):
        super(self.__class__, self).__init__()
        self.voice = voice
        self.pitch_adjustment = pitch_adjustment
        self.words_per_minute = words_per_minute
