### ISSUE TITLE
Jasper on Raspian

### ISSUE THREAD

**Issue by Palahace** [jasperproject/jasper-client#447]
No handlers could be found for logger "client.vocabcompiler"
Traceback (most recent call last):
  File "jasper.py", line 13, in <module>
    from client.conversation import Conversation
  File "/root/jasper/client/conversation.py", line 3, in <module>
    from notifier import Notifier
  File "/root/jasper/client/notifier.py", line 5, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/background.py", line 4, in <module>
    from apscheduler.schedulers.base import BaseScheduler
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 17, in <module>
    from apscheduler.jobstores.memory import MemoryJobStore
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/jobstores/memory.py", line 4, in <module>
    from apscheduler.util import datetime_to_utc_timestamp
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/util.py", line 278, in <module>
    if six.PY2:
AttributeError: 'module' object has no attribute 'PY2'

Whats all this mean??

**Comment by brad999** [comment]
Try installing six:
pip install six

Or upgrading:
pip install --upgrade six
