### ISSUE TITLE
******************************************************* *             JASPER - THE TALKING COMPUTER           * * (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis * ******************************************************* WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts' ERROR:root:Error occured! Traceback (most recent call last):   File "./../jasper.py", line 143, in <module>     app = Jasper()   File "./../jasper.py", line 106, in __init__     stt_passive_engine_class.get_passive_instance(),   File "/home/pi/Downloads/jasper/client/stt.py", line 48, in get_passive_instance     return cls.get_instance('keyword', phrases)   File "/home/pi/Downloads/jasper/client/stt.py", line 34, in get_instance     config = cls.get_config()   File "/home/pi/Downloads/jasper/client/stt.py", line 143, in get_config     config['hmm_dir'] = profile['pocketsphinx']['hmm_dir'] TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by mastanimaru** [jasperproject/jasper-client#470]

**Comment by mastanimaru** [comment]
Please, help me resolve this issue

**Comment by Azelphur** [comment]
Read the documentation for setting up PocketSphinx at http://jasperproject.github.io/documentation/configuration/

This issue is because you didn't specify a hmm_dir in your profile.yml

**Comment by mastanimaru** [comment]
I've already added hmm_dir in profile.yml . Still the error persists

**Comment by Azelphur** [comment]
Show your config file.

**Comment by mvarrieur** [comment]
This is the worst github issue title I've ever seen...

**Comment by mattcurrycom** [comment]
These are personal configuration issues; NOT code issues.  Please take them to the forums.  DEVs, please feel free to repeat this to others. This is Matt Curry, I run the forums for you guys.

**Comment by Holzhaus** [comment]
Exactly. Please just ask here: https://groups.google.com/forum/#!forum/jasper-support-forum
Closing this.
