### ISSUE TITLE
ERROR:client.vocabcompiler:Fatal compilation Error occured

### ISSUE THREAD

**Issue by IndiNijhof** [jasperproject/jasper-client#471]
I keep getting the error as shown below. The FTS file and the G2P binary are where the should be so have no idea what's causing this error.

```
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
DEBUG:client.diagnose:Checking network connection to server 'www.google.com'...
DEBUG:client.diagnose:Network connection working
DEBUG:__main__:Trying to read config file: '/home/pi/.jasper/profile.yml'
DEBUG:client.diagnose:Checking python import 'pocketsphinx'...
DEBUG:client.diagnose:Python module 'pocketsphinx' found: '/usr/lib/python2.7/dist-packages/pocketsphinx.so'
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
DEBUG:client.diagnose:Checking executable 'aplay'...
DEBUG:client.diagnose:Executable 'aplay' found: '/usr/bin/aplay'
DEBUG:client.diagnose:Checking executable 'espeak'...
DEBUG:client.diagnose:Executable 'espeak' found: '/usr/bin/espeak'
INFO:client.vocabcompiler:Starting compilation...
DEBUG:client.vocabcompiler:Compiling languagemodel...
DEBUG:client.vocabcompiler:Creating vocab file: '/tmp/tmpIM7PXA.vocab'
DEBUG:cmuclmtk:text2wfreq : Reading text from standard input...
DEBUG:cmuclmtk:text2wfreq : Done.
DEBUG:cmuclmtk:Command 'text2wfreq -hash 1000000 -verbosity 2' returned with exit code '0'.
DEBUG:cmuclmtk:wfreq2vocab : Will generate a vocabulary containing the most
DEBUG:cmuclmtk:frequent 20000 words. Reading wfreq stream from stdin...
DEBUG:cmuclmtk:wfreq2vocab : Done.
DEBUG:cmuclmtk:Command 'wfreq2vocab -verbosity 2 -records 1000000' returned with exit code '0'.
DEBUG:client.vocabcompiler:Creating languagemodel file: '/home/pi/.jasper/vocabularies/pocketsphinx-vocabulary/keyword/languagemodel'
DEBUG:cmuclmtk:text2idngram
DEBUG:cmuclmtk:Vocab                  : /tmp/tmpIM7PXA.vocab
DEBUG:cmuclmtk:Output idngram         : /tmp/tmpRFaHuY.idngram
DEBUG:cmuclmtk:N-gram buffer size     : 100
DEBUG:cmuclmtk:Hash table size        : 2000000
DEBUG:cmuclmtk:Temp directory         : cmuclmtk-USoiam
DEBUG:cmuclmtk:Max open files         : 20
DEBUG:cmuclmtk:FOF size               : 10
DEBUG:cmuclmtk:n                      : 3
DEBUG:cmuclmtk:Initialising hash table...
DEBUG:cmuclmtk:Reading vocabulary...
DEBUG:cmuclmtk:Allocating memory for the n-gram buffer...
DEBUG:cmuclmtk:Reading text into the n-gram buffer...
DEBUG:cmuclmtk:20,000 n-grams processed for each ".", 1,000,000 for each line.
DEBUG:cmuclmtk:Sorting n-grams...
DEBUG:cmuclmtk:Writing sorted n-grams to temporary file cmuclmtk-USoiam/1
DEBUG:cmuclmtk:Merging 1 temporary files...
DEBUG:cmuclmtk:2-grams occurring:       N times         > N times       Sug. -spec_num value
DEBUG:cmuclmtk:0                                                     35              45
DEBUG:cmuclmtk:1                                     34               1              11
DEBUG:cmuclmtk:2                                      0               1              11
DEBUG:cmuclmtk:3                                      0               1              11
DEBUG:cmuclmtk:4                                      0               1              11
DEBUG:cmuclmtk:5                                      0               1              11
DEBUG:cmuclmtk:6                                      0               1              11
DEBUG:cmuclmtk:7                                      0               1              11
DEBUG:cmuclmtk:8                                      0               1              11
DEBUG:cmuclmtk:9                                      0               1              11
DEBUG:cmuclmtk:10                                     0               1              11
DEBUG:cmuclmtk:3-grams occurring:       N times         > N times       Sug. -spec_num value
DEBUG:cmuclmtk:0                                                     51              61
DEBUG:cmuclmtk:1                                     51               0              10
DEBUG:cmuclmtk:2                                      0               0              10
DEBUG:cmuclmtk:3                                      0               0              10
DEBUG:cmuclmtk:4                                      0               0              10
DEBUG:cmuclmtk:5                                      0               0              10
DEBUG:cmuclmtk:6                                      0               0              10
DEBUG:cmuclmtk:7                                      0               0              10
DEBUG:cmuclmtk:8                                      0               0              10
DEBUG:cmuclmtk:9                                      0               0              10
DEBUG:cmuclmtk:10                                     0               0              10
DEBUG:cmuclmtk:text2idngram : Done.
DEBUG:cmuclmtk:Command 'text2idngram -vocab /tmp/tmpIM7PXA.vocab -idngram /tmp/tmpRFaHuY.idngram -buffer 100 -hash 2000000 -files 20 -verbosity 2 -n 3 -fof_size 10' returned with exit code '0'.
DEBUG:cmuclmtk:Warning : OOV fraction specified, but will not be used, since vocab type is not 2.
DEBUG:cmuclmtk:n : 3
DEBUG:cmuclmtk:Input file : /tmp/tmpRFaHuY.idngram     (binary format)
DEBUG:cmuclmtk:Output files :
DEBUG:cmuclmtk:ARPA format   : /home/pi/.jasper/vocabularies/pocketsphinx-vocabulary/keyword/languagemodel
DEBUG:cmuclmtk:Vocabulary file : /tmp/tmpIM7PXA.vocab
DEBUG:cmuclmtk:Cutoffs :
DEBUG:cmuclmtk:2-gram : 0     3-gram : 0
DEBUG:cmuclmtk:Vocabulary type : Open - type 1
DEBUG:cmuclmtk:Minimum unigram count : 0
DEBUG:cmuclmtk:Zeroton fraction : 1
DEBUG:cmuclmtk:Counts will be stored in two bytes.
DEBUG:cmuclmtk:Count table size : 65535
DEBUG:cmuclmtk:Discounting method : Good-Turing
DEBUG:cmuclmtk:Discounting ranges :
DEBUG:cmuclmtk:1-gram : 1     2-gram : 7     3-gram : 7
DEBUG:cmuclmtk:Memory allocation for tree structure :
DEBUG:cmuclmtk:Allocate 100 MB of memory, shared equally between all n-gram tables.
DEBUG:cmuclmtk:Back-off weight storage :
DEBUG:cmuclmtk:Back-off weights will be stored in four bytes.
DEBUG:cmuclmtk:Reading vocabulary.
DEBUG:cmuclmtk:read_wlist_into_siht: a list of 20 words was read from "/tmp/tmpIM7PXA.vocab".
DEBUG:cmuclmtk:read_wlist_into_array: a list of 20 words was read from "/tmp/tmpIM7PXA.vocab".
DEBUG:cmuclmtk:WARNING: <s> appears as a vocabulary item, but is not labelled as a
DEBUG:cmuclmtk:context cue.
DEBUG:cmuclmtk:Allocated space for 3571428 2-grams.
DEBUG:cmuclmtk:Allocated space for 8333333 3-grams.
DEBUG:cmuclmtk:table_size 21
DEBUG:cmuclmtk:Allocated 57142848 bytes to table for 2-grams.
DEBUG:cmuclmtk:Allocated (2+33333332) bytes to table for 3-grams.
DEBUG:cmuclmtk:Processing id n-gram file.
DEBUG:cmuclmtk:20,000 n-grams processed for each ".", 1,000,000 for each line.
DEBUG:cmuclmtk:Calculating discounted counts.
DEBUG:cmuclmtk:Warning : 1-gram : Discounting range is 1; setting P(zeroton)=P(singleton).
DEBUG:cmuclmtk:Discounted value : 0.89
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 6.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 5.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 4.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 3.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 2.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 1.
DEBUG:cmuclmtk:Warning : 2-gram : Discounting range of 1 is equivalent to excluding
DEBUG:cmuclmtk:singletons.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 0.
DEBUG:cmuclmtk:Warning : 2-gram : Discounting is disabled.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 6.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 5.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 4.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 3.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 2.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 1.
DEBUG:cmuclmtk:Warning : 3-gram : Discounting range of 1 is equivalent to excluding
DEBUG:cmuclmtk:singletons.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 0.
DEBUG:cmuclmtk:Warning : 3-gram : Discounting is disabled.
DEBUG:cmuclmtk:Unigrams's discount mass is 0.0350877 (n1/N = 0.333333)
DEBUG:cmuclmtk:2 zerotons, P(zeroton) = 0.0175439 P(singleton) = 0.0175439
DEBUG:cmuclmtk:P(zeroton) was reduced to 0.0175438593 (1.000 of P(singleton))
DEBUG:cmuclmtk:prob[UNK] = 0.0175439
DEBUG:cmuclmtk:Incrementing contexts...
DEBUG:cmuclmtk:Calculating back-off weights...
DEBUG:cmuclmtk:Writing out language model...
DEBUG:cmuclmtk:ARPA-style 3-gram will be written to /home/pi/.jasper/vocabularies/pocketsphinx-vocabulary/keyword/languagemodel
DEBUG:cmuclmtk:idngram2lm : Done.
DEBUG:cmuclmtk:Command 'idngram2lm -idngram /tmp/tmpRFaHuY.idngram -vocab /tmp/tmpIM7PXA.vocab -vocab_type 1 -oov_fraction 0.5 -min_unicount 0 -verbosity 2 -n 3 -arpa /home/pi/.jasper/vocabularies/pocketsphinx-vocabulary/keyword/languagemodel -bin_input' returned with exit code '0'.
DEBUG:client.vocabcompiler:Getting words from vocab file and removing it afterwards...
DEBUG:client.vocabcompiler:Starting dictionary...
DEBUG:client.vocabcompiler:Getting phonemes for 18 words...
DEBUG:client.diagnose:Checking executable 'phonetisaurus-g2p'...
DEBUG:client.diagnose:Executable 'phonetisaurus-g2p' found: '/usr/bin/phonetisaurus-g2p'
DEBUG:client.g2p:Using FST model: '/home/pi/phonetisaurus/g014b2b.fst'
DEBUG:client.g2p:Converting 18 words to phonemes
ERROR:client.g2p:Command 'phonetisaurus-g2p --model=/home/pi/phonetisaurus/g014b2b.fst --input=/tmp/tmpVxNiTn.g2p --words --isfile' return with exit status -4
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 271, in _compile_vocabulary
    self._compile_dictionary(vocabulary, self.dictionary_file)
  File "/home/pi/jasper/client/vocabcompiler.py", line 321, in _compile_dictionary
    phonemes = g2pconverter.translate(words)
  File "/home/pi/jasper/client/g2p.py", line 130, in translate
    output = self._translate_words(words)
  File "/home/pi/jasper/client/g2p.py", line 119, in _translate_words
    nbest=self.nbest)
  File "/home/pi/jasper/client/g2p.py", line 56, in execute
    raise OSError("Command execution failed")
OSError: Command execution failed
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 143, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 106, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
OSError: Command execution failed
```

**Comment by WirelessMind** [comment]
same error.
Any solution?

**Comment by IndiNijhof** [comment]
In my case the error was caused by an invalid FST file. I solved it by recompiling the fst library and then recompiling the file.

**Comment by ganesh125** [comment]
i have this problem anyone have solution for that


No handlers could be found for logger "cmuclmtk"
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 269, in _compile_vocabulary
    vocabulary = self._compile_languagemodel(text, self.languagemodel_file)
  File "/home/pi/jasper/client/vocabcompiler.py", line 290, in _compile_languagemodel
    cmuclmtk.text2vocab(text, vocab_file)
NameError: global name 'cmuclmtk' is not defined
ERROR:root:Error occured!
Traceback (most recent call last):
  File "./jasper.py", line 146, in <module>
    app = Jasper()
  File "./jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
NameError: global name 'cmuclmtk' is not defined

**Comment by ganesh125** [comment]
anyone have solution

**Comment by wrboliveira** [comment]
@IndiNijhof Quais os comandos que vc usou para compilar e recompilar tudo estou com o mesmo erro, mas estou tentando inserir a linguagem brasilian pt_BR no jasper.
