### ISSUE TITLE
DEV Branch: Why is witai-stt English only?

### ISSUE THREAD

**Issue by codeurfou** [jasperproject/jasper-client#480]
Hello!

I've tested wit.ai STT in French. It works if I comment the code about "Only english restriction" :) (DEV Branch)

Language is configurable on Wit.ai website. So, I suggest to remove this restriction...?

Thanks for your work!

**Comment by ncoletto** [comment]
Hi! 
Can you please give a detailed guideline on how to implement Jasper with Wit.ai and using another language than english? for instance French? Thanks!!!

I am able to use english, but when I choose another language (I tried 3 at least), Jasper returns the following error:


INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.wit.ai
DEBUG:requests.packages.urllib3.connectionpool:"POST /speech?v=20150101 HTTP/1.1" 200 121
Traceback (most recent call last):
  File "./jasper.py", line 141, in <module>
    app.run()
  File "./jasper.py", line 111, in run
    conversation.handleForever()
  File "/home/pi/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/jasper/client/mic.py", line 179, in passiveListen
    transcribed = self.passive_stt_engine.transcribe(f)
  File "/home/pi/jasper/client/stt.py", line 613, in transcribe
    transcribed = [text.upper()]
AttributeError: 'NoneType' object has no attribute 'upper'
INFO:apscheduler.scheduler:Scheduler has been shut down

**Comment by andweber** [comment]
wit.ai restriction is changed in dev branch with #507

@ncoletto:
use the "jasper-dev" branch. This version already supports multi-languages in principle. Please note that its a development branch.
