### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'hmm'

### ISSUE THREAD

**Issue by d3im** [jasperproject/jasper-client#482]
Hi, have this error, need some help:
```
$ ./jasper.py --debug
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
DEBUG:client.diagnose:Checking network connection to server 'www.google.com'...
DEBUG:client.diagnose:Network connection working
DEBUG:__main__:Trying to read config file: '/home/user/.jasper/profile.yml'
DEBUG:client.diagnose:Checking python import 'pocketsphinx'...
DEBUG:client.diagnose:Python package 'pocketsphinx' found: '/usr/lib/python2.7/site-packages/pocketsphinx/__init__.py'
DEBUG:client.diagnose:Checking executable 'aplay'...
DEBUG:client.diagnose:Executable 'aplay' found: '/usr/bin/aplay'
DEBUG:client.diagnose:Checking executable 'flite'...
DEBUG:client.diagnose:Executable 'flite' found: '/usr/bin/flite'
DEBUG:client.vocabcompiler:compiled_revision is 'bb74ae36d130ef20de710e3a77b43424b8fa774f'
ERROR:root:Error occured!
Traceback (most recent call last):
  File "./jasper.py", line 143, in <module>
    app = Jasper()
  File "./jasper.py", line 106, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/user/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/user/jasper/client/stt.py", line 42, in get_instance
    instance = cls(**config)
  File "/home/user/jasper/client/stt.py", line 126, in __init__
    **vocabulary.decoder_kwargs)
TypeError: __init__() got an unexpected keyword argument 'hmm'
```

my profile:
```
carrier: ''
first_name: xxx
gmail_password: ''
last_name: yyy
phone_number: ''
prefers_email: true
stt_engine: sphinx
pocketsphinx:
  fst_model: '/home/user/g014b2b/g014b2b.fst'
  hmm_dir: '/usr/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k'
timezone: Europe/Prague
tts_engine: flite-tts
flite-tts:
  voice: 'slt'
```

**Comment by Holzhaus** [comment]
What pocketsphinx version are you using?

**Comment by d3im** [comment]
I'm using pocketsphinx 0.8
I'm also on Gentoo and pocketsphinx and sphinxbase was installed via portage package system with python use flag enabled (https://packages.gentoo.org/packages/app-accessibility/pocketsphinx).

**Comment by d3im** [comment]
I realised I had installed newest pocketsphinx python package over pip, so I uninstalled it and recompiled pocketsphinx and sphinxbase packages with python use flag. Now I get this:
```
$ ./jasper.py --debug
No handlers could be found for logger "cmuclmtk"
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
DEBUG:client.diagnose:Checking network connection to server 'www.google.com'...
DEBUG:client.diagnose:Network connection working
DEBUG:__main__:Trying to read config file: '/home/user/.jasper/profile.yml'
DEBUG:client.diagnose:Checking python import 'pocketsphinx'...
DEBUG:client.diagnose:Python module 'pocketsphinx' found: '/usr/lib/python2.7/site-packages/pocketsphinx.so'
DEBUG:client.diagnose:Checking executable 'aplay'...
DEBUG:client.diagnose:Executable 'aplay' found: '/usr/bin/aplay'
DEBUG:client.diagnose:Checking executable 'flite'...
DEBUG:client.diagnose:Executable 'flite' found: '/usr/bin/flite'
DEBUG:client.vocabcompiler:compiled_revision is 'bb74ae36d130ef20de710e3a77b43424b8fa774f'
DEBUG:client.brain:Looking for modules in: '/home/user/jasper/client/modules'
DEBUG:client.brain:Found module 'Birthday' with words: ['BIRTHDAY']
DEBUG:client.brain:Found module 'Gmail' with words: ['EMAIL', 'INBOX']
DEBUG:client.brain:Found module 'HN' with words: ['HACKER', 'NEWS', 'YES', 'NO', 'FIRST', 'SECOND', 'THIRD']
DEBUG:client.brain:Found module 'Joke' with words: ['JOKE', 'KNOCK KNOCK']
DEBUG:client.brain:Found module 'Life' with words: ['MEANING', 'OF', 'LIFE']
DEBUG:client.brain:Found module 'MPDControl' with words: ['MUSIC', 'SPOTIFY']
DEBUG:client.brain:Found module 'News' with words: ['NEWS', 'YES', 'NO', 'FIRST', 'SECOND', 'THIRD']
DEBUG:client.brain:Found module 'Notifications' with words: ['FACEBOOK', 'NOTIFICATION']
DEBUG:client.brain:Found module 'Time' with words: ['TIME']
DEBUG:client.brain:Found module 'Unclear' with words: []
DEBUG:client.brain:Found module 'Weather' with words: ['WEATHER', 'TODAY', 'TOMORROW']
INFO:client.vocabcompiler:Starting compilation...
DEBUG:client.vocabcompiler:Compiling languagemodel...
DEBUG:client.vocabcompiler:Creating vocab file: '/tmp/tmpow8aFI.vocab'
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/user/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/user/jasper/client/vocabcompiler.py", line 269, in _compile_vocabulary
    vocabulary = self._compile_languagemodel(text, self.languagemodel_file)
  File "/home/user/jasper/client/vocabcompiler.py", line 290, in _compile_languagemodel
    cmuclmtk.text2vocab(text, vocab_file)
NameError: global name 'cmuclmtk' is not defined
ERROR:root:Error occured!
Traceback (most recent call last):
  File "./jasper.py", line 143, in <module>
    app = Jasper()
  File "./jasper.py", line 107, in __init__
    stt_engine_class.get_active_instance())
  File "/home/user/jasper/client/stt.py", line 53, in get_active_instance
    return cls.get_instance('default', phrases)
  File "/home/user/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/user/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
NameError: global name 'cmuclmtk' is not defined
```

**Comment by d3im** [comment]
Seems to be $PATH problem. Now it's running but I need to test it if it understands what I'm trying to say :-)

**Comment by piegamesde** [comment]
> I realised I had installed newest pocketsphinx python package over pip, so I uninstalled it and recompiled pocketsphinx and sphinxbase packages with python use flag

What exactly did you do to resolve this problem?

**Comment by WesleyThompson** [comment]
Lol did you figure this out either? Paging @d3im I'd really love to know what you did lol

**Comment by akoliya01** [comment]
Hi, 
I am facing this error.
Anyone have a idea how rectify this ?


ERROR:root:Error occured!
Traceback (most recent call last):
  File "./jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "./jasper/jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 42, in get_instance
    instance = cls(**config)
  File "/home/pi/jasper/client/stt.py", line 126, in __init__
    **vocabulary.decoder_kwargs)
TypeError: __init__() got an unexpected keyword argument 'hmm'


This is my profile.yml

carrier: ''
first_name: Raspberry
gmail_password: ''
last_name: pi
phone_number: ''
prefers_email: false
stt_engine: sphinx
stt_engine: sphinx
pocketsphinx:
  fst_model: '/home/pi/phonetisaurus/g014b2b.fst'                             
  hmm_dir: '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k'
tts_engine: pico-tts
