### ISSUE TITLE
install -r jasper/client/requirements.txt issue 

### ISSUE THREAD

**Issue by ShunJianLee** [jasperproject/jasper-client#495]
When i type sudo pip install -r jasper/client/requirements.txt in the terminal.

Could not open requirements file: [Errno 2] No such file or directory: 'jasper/client/requirements.txt'
Storing debug log for failure in /root/.pip/pip.log

How to solve this problem?

**Comment by crespum** [comment]
It looks like you're not on the right directory. Have you followed [the documentation tutorial](http://jasperproject.github.io/documentation/installation/)?

If you've cloned the repository with this command ```git clone https://github.com/jasperproject/jasper-client.git jasper``` just do ```cd ~``` and your command should work. I assume you are using master branch.

If you've cloned the repository using ```git clone https://github.com/jasperproject/jasper-client.git``` (notice that there is not the last parameter that indicates the name of the folder where it's going to be cloned), just do ```cd ~``` and ```sudo pip install -r jasper-client/client/requirements.txt```.

In jasper-dev, there isn't a ```client``` subdirectory anymore so just do ```sudo pip install -r jasper-client/requirements.txt``` or ```sudo pip install -r jasper/requirements.txt```.

**Comment by ShunJianLee** [comment]
Thanks a lot @crespum

When i retype the directory again. There are some error happened on below attachments. 
May i know what is the problem? 

pi@raspberrypi:~ $ sudo pip install -r jasper/client/requirements.txt
Downloading/unpacking APScheduler==3.0.1 (from -r jasper/client/requirements.txt (line 2))
  Downloading APScheduler-3.0.1-py2.py3-none-any.whl (47kB): 47kB downloaded
Downloading/unpacking argparse==1.2.2 (from -r jasper/client/requirements.txt (line 3))
  Downloading argparse-1.2.2-py2.py3-none-any.whl
Downloading/unpacking mock==1.0.1 (from -r jasper/client/requirements.txt (line 4))
  Downloading mock-1.0.1.zip (861kB): 861kB downloaded
  Running setup.py (path:/tmp/pip-build-oB8wKX/mock/setup.py) egg_info for package mock
    
    warning: no files found matching '*.png' under directory 'docs'
    warning: no files found matching '*.css' under directory 'docs'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no files found matching '*.js' under directory 'docs'
Downloading/unpacking pytz==2014.10 (from -r jasper/client/requirements.txt (line 5))
  Downloading pytz-2014.10-py2.py3-none-any.whl (477kB): 477kB downloaded
Downloading/unpacking PyYAML==3.11 (from -r jasper/client/requirements.txt (line 6))
  Downloading PyYAML-3.11.zip (371kB): 371kB downloaded
  Running setup.py (path:/tmp/pip-build-oB8wKX/PyYAML/setup.py) egg_info for package PyYAML
    
Downloading/unpacking requests==2.5.0 (from -r jasper/client/requirements.txt (line 7))
  Downloading requests-2.5.0-py2.py3-none-any.whl (464kB): 464kB downloaded
Downloading/unpacking cmuclmtk==0.1.5 (from -r jasper/client/requirements.txt (line 10))
  Downloading cmuclmtk-0.1.5.tar.gz
  Running setup.py (path:/tmp/pip-build-oB8wKX/cmuclmtk/setup.py) egg_info for package cmuclmtk
    
Downloading/unpacking beautifulsoup4==4.3.2 (from -r jasper/client/requirements.txt (line 13))
  Downloading beautifulsoup4-4.3.2.tar.gz (143kB): 143kB downloaded
  Running setup.py (path:/tmp/pip-build-oB8wKX/beautifulsoup4/setup.py) egg_info for package beautifulsoup4
    
Downloading/unpacking semantic==1.0.3 (from -r jasper/client/requirements.txt (line 14))
  Downloading semantic-1.0.3.tar.gz
  Running setup.py (path:/tmp/pip-build-oB8wKX/semantic/setup.py) egg_info for package semantic
    
Downloading/unpacking facebook-sdk==0.4.0 (from -r jasper/client/requirements.txt (line 17))
  Downloading facebook-sdk-0.4.0.tar.gz
  Running setup.py (path:/tmp/pip-build-oB8wKX/facebook-sdk/setup.py) egg_info for package facebook-sdk
    
Downloading/unpacking feedparser==5.1.3 (from -r jasper/client/requirements.txt (line 20))
  Downloading feedparser-5.1.3.zip (1.2MB): 1.2MB downloaded
  Running setup.py (path:/tmp/pip-build-oB8wKX/feedparser/setup.py) egg_info for package feedparser
    
Downloading/unpacking python-dateutil==2.3 (from -r jasper/client/requirements.txt (line 23))
  Downloading python_dateutil-2.3-py2.py3-none-any.whl (173kB): 173kB downloaded
Downloading/unpacking python-mpd==0.3.0 (from -r jasper/client/requirements.txt (line 26))
  Downloading python-mpd-0.3.0.tar.bz2
  Running setup.py (path:/tmp/pip-build-oB8wKX/python-mpd/setup.py) egg_info for package python-mpd
    
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from APScheduler==3.0.1->-r jasper/client/requirements.txt (line 2))
Downloading/unpacking tzlocal (from APScheduler==3.0.1->-r jasper/client/requirements.txt (line 2))
  Downloading tzlocal-1.2.2.tar.gz
  Running setup.py (path:/tmp/pip-build-oB8wKX/tzlocal/setup.py) egg_info for package tzlocal
    
Downloading/unpacking futures; python_version < "3.2" (from APScheduler==3.0.1->-r jasper/client/requirements.txt (line 2))
  Downloading futures-3.0.5-py2-none-any.whl
Downloading/unpacking quantities (from semantic==1.0.3->-r jasper/client/requirements.txt (line 14))
  Downloading quantities-0.11.1.zip (105kB): 105kB downloaded
  Running setup.py (path:/tmp/pip-build-oB8wKX/quantities/setup.py) egg_info for package quantities
    
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python2.7/dist-packages (from semantic==1.0.3->-r jasper/client/requirements.txt (line 14))
Installing collected packages: APScheduler, argparse, mock, pytz, PyYAML, requests, cmuclmtk, beautifulsoup4, semantic, facebook-sdk, feedparser, python-dateutil, python-mpd, tzlocal, futures, quantities
  Found existing installation: argparse 1.2.1
    Not uninstalling argparse at /usr/lib/python2.7, owned by OS
  Running setup.py install for mock
    
    warning: no files found matching '*.png' under directory 'docs'
    warning: no files found matching '*.css' under directory 'docs'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no files found matching '*.js' under directory 'docs'
  Could not find .egg-info directory in install record for mock==1.0.1 (from -r jasper/client/requirements.txt (line 4))
  Running setup.py install for PyYAML
    checking if libyaml is compilable
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-armv7l-2.7/check_libyaml.c -o build/temp.linux-armv7l-2.7/check_libyaml.o
    build/temp.linux-armv7l-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.
    
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
    
  Could not find .egg-info directory in install record for PyYAML==3.11 (from -r jasper/client/requirements.txt (line 6))
  Found existing installation: requests 2.4.3
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for cmuclmtk
    
  Could not find .egg-info directory in install record for cmuclmtk==0.1.5 (from -r jasper/client/requirements.txt (line 10))
  Running setup.py install for beautifulsoup4
    
  Could not find .egg-info directory in install record for beautifulsoup4==4.3.2 (from -r jasper/client/requirements.txt (line 13))
  Running setup.py install for semantic
    
  Could not find .egg-info directory in install record for semantic==1.0.3 (from -r jasper/client/requirements.txt (line 14))
  Running setup.py install for facebook-sdk
    
  Could not find .egg-info directory in install record for facebook-sdk==0.4.0 (from -r jasper/client/requirements.txt (line 17))
  Running setup.py install for feedparser
    
  Could not find .egg-info directory in install record for feedparser==5.1.3 (from -r jasper/client/requirements.txt (line 20))
  Running setup.py install for python-mpd
    
  Could not find .egg-info directory in install record for python-mpd==0.3.0 (from -r jasper/client/requirements.txt (line 26))
  Running setup.py install for tzlocal
    
  Could not find .egg-info directory in install record for tzlocal (from APScheduler==3.0.1->-r jasper/client/requirements.txt (line 2))
  Running setup.py install for quantities
    UPDATING build/lib.linux-armv7l-2.7/quantities/_version.py
    set build/lib.linux-armv7l-2.7/quantities/_version.py to '0+unknown'
    
  Could not find .egg-info directory in install record for quantities (from semantic==1.0.3->-r jasper/client/requirements.txt (line 14))
Successfully installed APScheduler argparse mock pytz PyYAML requests cmuclmtk beautifulsoup4 semantic facebook-sdk feedparser python-dateutil python-mpd tzlocal futures quantities
Cleaning up...

**Comment by crespum** [comment]
Can it be related to [this issue](https://github.com/jupyter/notebook/issues/1224)? Have you run ```sudo pip install --upgrade setuptools```?

**Comment by ShunJianLee** [comment]
@crespum 
when i run sudo pip install --upgrade setuptools. Can you give me your skype id? 

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
