### ISSUE TITLE
jasper configuration 

### ISSUE THREAD

**Issue by ShunJianLee** [jasperproject/jasper-client#496]
May i know why after i press jasper configuration it will shown up this problem?
pi@raspberrypi:~ $ /home/pi/jasper/jasper.py
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 12, in <module>
    from client import tts, stt, jasperpath, diagnose
  File "/home/pi/jasper/client/tts.py", line 41, in <module>
    import diagnose
  File "/home/pi/jasper/client/diagnose.py", line 9, in <module>
    import pip.req
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

**Comment by GeoBeBee** [comment]
I had the same problem, and then several more, see this:
[https://github.com/GeoBeBee/mySystem/blob/master/Jasper-dev_onPocketPhinx_5preAlpha.txt](https://github.com/GeoBeBee/mySystem/blob/master/Jasper-dev_onPocketPhinx_5preAlpha.txt)

**Comment by ShunJianLee** [comment]
@GeoBeBee do you face this issues before?

pi@raspberrypi:~ $ /home/pi/jasper/jasper.pyNo handlers could be found for logger "cmuclmtk"
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 143, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 88, in __init__
    stt_engine_class = stt.get_engine_by_slug(stt_engine_slug)
  File "/home/pi/jasper/client/stt.py", line 648, in get_engine_by_slug
    "dependencies, etc.)") % slug)
ValueError: STT engine 'sphinx' is not available (due to missing dependencies, missing dependencies, etc.)

**Comment by GeoBeBee** [comment]
No I didn't, but this looks interesting: https://docs.python.org/3.1/library/logging.html
Sure you have everything installed?

**Comment by mattcurrycom** [comment]
Its an issue with Requests, I ran into it as well. Remove it and reinstall it.

**Comment by ganesh125** [comment]
i have this problem how to fix it...somebody guide me

No handlers could be found for logger "cmuclmtk"
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:root:Error occured!
Traceback (most recent call last):
  File "./jasper.py", line 146, in <module>
    app = Jasper()
  File "./jasper.py", line 80, in __init__
    self.config = yaml.safe_load(f)
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python2.7/dist-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/usr/local/lib/python2.7/dist-packages/yaml/scanner.py", line 149, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/usr/local/lib/python2.7/dist-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not found expected ':'", self.get_mark())
ScannerError: while scanning a simple key
  in "/home/pi/.jasper/profile.yml", line 13, column 1
could not found expected ':'
  in "/home/pi/.jasper/profile.yml", line 14, column 1

**Comment by G10DRAS** [comment]
seems some problem with profile.yml. could you check line 13 and 14. what is there?
