### ISSUE TITLE
Error :  global name 'cmuclmtk' is not defined

### ISSUE THREAD

**Issue by ShunJianLee** [jasperproject/jasper-client#501]
Anyone have the idea to solve this problem? 

pi@raspberrypi:~ $ /home/pi/jasper/jasper.py
*******************************************************
* JASPER - THE TALKING COMPUTER *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
File "/home/pi/jasper/client/vocabcompiler.py", line 163, in compile
self._compile_vocabulary(phrases)
File "/home/pi/jasper/client/vocabcompiler.py", line 269, in _compile_vocabulary
vocabulary = self._compile_languagemodel(text, self.languagemodel_file)
File "/home/pi/jasper/client/vocabcompiler.py", line 290, in _compile_languagemodel
cmuclmtk.text2vocab(text, vocab_file)
NameError: global name 'cmuclmtk' is not defined
ERROR:root:Error occured!
Traceback (most recent call last):
File "/home/pi/jasper/jasper.py", line 143, in <module>
app = Jasper()
File "/home/pi/jasper/jasper.py", line 106, in __init__
stt_passive_engine_class.get_passive_instance(),
File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
return cls.get_instance('keyword', phrases)
File "/home/pi/jasper/client/stt.py", line 40, in get_instance
vocabulary.compile(phrases)
File "/home/pi/jasper/client/vocabcompiler.py", line 171, in compile
raise e
NameError: global name 'cmuclmtk' is not defined

**Comment by GeoBeBee** [comment]
Did you install cmuclmtk as per: http://jasperproject.github.io/documentation/installation/#installing-dependencies ?

**Comment by ShunJianLee** [comment]
@GeoBeBee thanks for your advise. Currently i am struggling with this issue. 
Does anyone know how to solve this? thanks 

pi@raspberrypi:~ $ /home/pi/jasper/jasper.py
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 13, in <module>
    from client.conversation import Conversation
  File "/home/pi/jasper/client/conversation.py", line 3, in <module>
    from notifier import Notifier
  File "/home/pi/jasper/client/notifier.py", line 4, in <module>
    from modules import Gmail
  File "/home/pi/jasper/client/modules/Gmail.py", line 5, in <module>
    from dateutil import parser
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 14, in <module>
    from six import text_type, binary_type, integer_types
ImportError: No module named six

**Comment by dmbuchta** [comment]
did you try `easy_install six`? If that doesn't work trying reinstalling pip.

**Comment by ShunJianLee** [comment]
@dmbuchta thanks for your advise. really appreciate it. 

May i know what is correct way to reinstall pip because the terminal not allow me to remove it. 

pi@raspberrypi:~ $ pip uninstall
You must give at least one requirement to uninstall (see "pip help uninstall")

**Comment by dmbuchta** [comment]
try this to uninstall: `python -m pip uninstall pip setuptools`
Look here for reinstall: [http://unix.stackexchange.com/questions/182308/install-python-pip-in-debian-wheezy](url)
