### ISSUE TITLE
Error: ImportError: No module named six 

### ISSUE THREAD

**Issue by ShunJianLee** [jasperproject/jasper-client#506]
Hello everyone, i am currently struggle with this issue? Does anyone know how to solve this? Thanks 

pi@raspberrypi:~ $ /home/pi/jasper/jasper.py
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 13, in <module>
    from client.conversation import Conversation
  File "/home/pi/jasper/client/conversation.py", line 3, in <module>
    from notifier import Notifier
  File "/home/pi/jasper/client/notifier.py", line 4, in <module>
    from modules import Gmail
  File "/home/pi/jasper/client/modules/Gmail.py", line 5, in <module>
    from dateutil import parser
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 14, in <module>
    from six import text_type, binary_type, integer_types
ImportError: No module named six

**Comment by aniketk21** [comment]
An `ImportError` occurred because you don't have the Python `six` module on your system.
Install it using `$ pip install six`.
