### ISSUE TITLE
Errors After Installation :No STT engine found for slug 'Pocketsphinx'

### ISSUE THREAD

**Issue by rkbilla** [jasperproject/jasper-client#533]
`mq(05:24:29)-(~)->~/jasper/jasper.py
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/root/jasper/jasper.py", line 143, in <module>
    app = Jasper()
  File "/root/jasper/jasper.py", line 88, in __init__
    stt_engine_class = stt.get_engine_by_slug(stt_engine_slug)
  File "/root/jasper/client/stt.py", line 639, in get_engine_by_slug
    raise ValueError("No STT engine found for slug '%s'" % slug)
ValueError: No STT engine found for slug 'Pocketsphinx'``

Can any one help me in this

**Comment by t-h-e** [comment]
Try importing "pocketsphinx" in python and see if that works. I had the same problem.

I simply had to install pocketsphinx with pip: "pip install pocketsphinx"

**Comment by rkbilla** [comment]
Requirement already satisfied (use --upgrade to upgrade): pocketsphinx in /usr/local/lib/python2.7/dist-packages

It saying and plz let me know where i have to "import pocketsphinx"

**Comment by t-h-e** [comment]
It's bad practice to hijack another thread (https://github.com/jasperproject/jasper-client/issues/433) and have a conversation in two threads about the same problem.

The error message is telling you 

> OSError: Can't find command 'phonetisaurus-g2p'! Please check if Phonetisaurus is installed and in your $PATH. `

And @G10DRAS already told you the answer:
> Check if Phonetisaurus is installed along with its dependencies, or try re-installing Phonetisaurus.

For help, look in the [documentation](http://jasperproject.github.io/documentation/installation/) under "Installing Phonetisaurus, m2m-aligner and MITLM"
