### ISSUE TITLE
Input Overflow issue

### ISSUE THREAD

**Issue by GitSujal** [jasperproject/jasper-client#537]
File "./../jasper.py", line 148, in <module>
    app.run()
  File "./../jasper.py", line 118, in run
    conversation.handleForever()
  File "/home/pi/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/jasper/client/mic.py", line 121, in passiveListen
    data = stream.read(CHUNK)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 605, in read
    return pa.read_stream(self._stream, num_frames)
IOError: [Errno Input overflowed] -9981
INFO:apscheduler.scheduler:Scheduler has been shut down

**Comment by aaronfranco** [comment]
Same issue here
```
DEBUG:client.conversation:Started to listen actively with threshold: 72.0
DEBUG:client.tts:Executing aplay -D plughw:1,0 /home/pi/jasper/static/audio/beep_hi.wav
DEBUG:client.tts:Output was: 'Playing WAVE '/home/pi/jasper/static/audio/beep_hi.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
'
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 151, in <module>
    app.run()
  File "/home/pi/jasper/jasper.py", line 121, in run
    conversation.handleForever()
  File "/home/pi/jasper/client/conversation.py", line 42, in handleForever
    input = self.mic.activeListenToAllOptions(threshold)
  File "/home/pi/jasper/client/mic.py", line 238, in activeListenToAllOptions
    data = self.resample(stream.read(CHUNK), RATE)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
IOError: [Errno -9981] Input overflowed
INFO:apscheduler.scheduler:Scheduler has been shut down
```

**Comment by G10DRAS** [comment]
Upping the chunk size (e.g. to 2048 or 4096) sometime solve the problem.
