### ISSUE TITLE
problem on the dev version 

### ISSUE THREAD

**Issue by TuxSeb** [jasperproject/jasper-client#544]
Hi, i have a problem when i launch jasper.py on the dev version, 

` File "/home/pi/jasper-client/jasper/plugin.py, line 5, in <module>
     import mad
ImportError: No module named mad `

**Comment by glop102** [comment]
i solved this issue by doing the following command
pip install  mad

this will install the "mad" module, whatever it does, on your system

**Comment by TuxSeb** [comment]
Thanks you ! it work ! Thanks !!

**Comment by danielhyt2** [comment]
I got the same error. When trying to install mad (pip install mad), I got these errors:

`pi@raspberrypi:~ $ pip install mad
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
`
