### ISSUE TITLE
jasper installing libraries error

### ISSUE THREAD

**Issue by ShunJianLee** [jasperproject/jasper-client#556]
Good day everyone, may i know what does this means? 

pi@raspberrypi:~ $ sudo pip install --upgrade setuptools
Cleaning up...
Exception:
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
status = self.run(options, args)
File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1097, in prepare_files
req_to_install, self.upgrade)
File "/usr/lib/python2.7/dist-packages/pip/index.py", line 194, in find_requirement
page = self.get_page(main_index_url, req)
File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in get_page
session=self.session,
File "/usr/lib/python2.7/dist-packages/pip/index.py", line 694, in get_page
req, link, "connection error: %s" % exc, url,
TypeError: __str returned non-string (type Error)
Storing debug log for failure in /root/.pip/pip.log

pi@raspberrypi:~ $ sudo pip install -r jasper/client/requirements.txt
Downloading/unpacking APScheduler==3.0.1 (from -r jasper/client/requirements.txt (line 2))
Cleaning up...
Exception:
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
status = self.run(options, args)
File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
File "/usr/lib/python2.7/dist-packages/pip/index.py", line 194, in find_requirement
page = self.get_page(main_index_url, req)
File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in get_page
session=self.session,
File "/usr/lib/python2.7/dist-packages/pip/index.py", line 694, in get_page
req, link, "connection error: %s" % exc, url,
TypeError: __str returned non-string (type Error)

Storing debug log for failure in /root/.pip/pip.log

**Comment by chrobione** [comment]
Both the pip errors are throwing the same error.
``` req, link, "connection error: %s" % exc, url,```

If I was getting this error, I would try something like ```ping  www.google.com``` to confirm two things.
1. DNS is working
2. That the pi can get to the internet

HTH
Chrobi

**Comment by ShunJianLee** [comment]
Thanks @chrobione for the advises. ;)
