### ISSUE TITLE
ValueError: No STT engine found for slug 'pocketsphinx' 

### ISSUE THREAD

**Issue by ShunJianLee** [jasperproject/jasper-client#557]
May i know how to solve this issues? 

pi@raspberrypi:~ $ /home/pi/jasper/jasper.py
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:Network not connected. This may prevent Jasper from running properly.
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 91, in __init__
    stt_engine_class = stt.get_engine_by_slug(stt_engine_slug)
  File "/home/pi/jasper/client/stt.py", line 639, in get_engine_by_slug
    raise ValueError("No STT engine found for slug '%s'" % slug)
ValueError: No STT engine found for slug 'pocketsphinx'

pi@raspberrypi:~ $ sudo nano ~/.jasper/profile.yml
carrier: ''
first_name: shun
gmail_password: ''
last_name: jian
phone_number: ''
prefers_email: false
stt_engine: pocketsphinx
pocketsphinx:
  fst_model: '../phonetisaurus/g014b2b.fst'                              #optional
  hmm_dir: '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' #optional

**Comment by G10DRAS** [comment]
Its not `pocketsphinx`, use `sphinx`

```
stt_engine: sphinx
pocketsphinx:
   fst_model: '<path to fst>'
   hmm_dir: '<path to acoustic model>'
```

**Comment by ShunJianLee** [comment]
@G10DRAS Thanks for your reply, may i know why the terminal cant find command 'phonetisaurus-g2p' ? 

pi@raspberrypi:~ $ /home/pi/jasper/jasper.py
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 271, in _compile_vocabulary
    self._compile_dictionary(vocabulary, self.dictionary_file)
  File "/home/pi/jasper/client/vocabcompiler.py", line 320, in _compile_dictionary
    g2pconverter = PhonetisaurusG2P(**PhonetisaurusG2P.get_config())
  File "/home/pi/jasper/client/g2p.py", line 90, in __new__
    "$PATH.")
OSError: Can't find command 'phonetisaurus-g2p'! Please check if Phonetisaurus is installed and in your $PATH.
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
OSError: Can't find command 'phonetisaurus-g2p'! Please check if Phonetisaurus is installed and in your $PATH.

**Comment by G10DRAS** [comment]
Have you compiled and installed `Phonetisaurus `?
Check Jasper doc, [Installing Phonetisaurus, m2m-aligner and MITLM]
http://jasperproject.github.io/documentation/installation/#installing-dependencies

**Comment by ShunJianLee** [comment]
@G10DRAS Yup,  i have install already. May i know how to locate 
FST model (g014b2b.fst) and the Hidden Markov Model directory (hub4wsj_sc_8k) ? 

pi@raspberrypi:~ $ /home/pi/jasper/jasper.py
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:Network not connected. This may prevent Jasper from running properly.
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 271, in _compile_vocabulary
    self._compile_dictionary(vocabulary, self.dictionary_file)
  File "/home/pi/jasper/client/vocabcompiler.py", line 320, in _compile_dictionary
    g2pconverter = PhonetisaurusG2P(**PhonetisaurusG2P.get_config())
  File "/home/pi/jasper/client/g2p.py", line 90, in __new__
    "$PATH.")
OSError: Can't find command 'phonetisaurus-g2p'! Please check if Phonetisaurus is installed and in your $PATH.
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
OSError: Can't find command 'phonetisaurus-g2p'! Please check if Phonetisaurus is installed and in your $PATH.


pi@raspberrypi:~ $ ls
blink1                  mitlm-0.4.1           pocketsphinx-0.8
cmuclmtk                mitlm-0.4.1.tar.gz    pocketsphinx-0.8.tar.gz
cv2.so                  Music                 Public
cv.py                   opencv                pyaudio
Desktop                 OpenCV-2.3.1          python_games
Documents               opencv-2.4.10         pywit
Downloads               opencv-2.4.10.zip     pywit-master
g014b2b.tgz             opencv_contrib        relay1.py
get-pip.py              opencv_contrib-3.0.0  scripts1
get-pip.py.1            opencv_contrib.zip    sketchbook
get-pip.py.2            openfst-1.3.4         speech2text.sh
git                     openfst-1.3.4.tar.gz  sphinxbase-0.8
gui_example.py          phonetisaurus         sphinxbase-0.8.tar.gz
is2013-conversion       PiAUISuite            sphinxbase-0.8.tar.gz.1
is2013-conversion.tgz   PiAUISuite.tar.gz     Templates
jasper                  Pictures              Videos
m2m-aligner-1.2         PIGPIO                wiringPi
m2m-aligner-1.2.tar.gz  pigpio.zip
Melissa-Core            playbook-opencv

**Comment by G10DRAS** [comment]
if you already compiled fst model then you will get `g014b2b.fst `under `g014b2b` dir.
and HMM you will get under` /usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k`.
