### ISSUE TITLE
Jasper won't accept commands

### ISSUE THREAD

**Issue by stevenwalton** [jasperproject/jasper-client#558]
So I can start jasper and it asks how it may be of service. Sometimes right after it starts I am able to activate it and get it to do something like tell me what time it is. After that, or most times starting, it does not accept any commands and does not recognize the keyword "Jasper". 

Here is the output. I am using the B+ image and followed the install instructions (couldn't get it running on Arch)

```
pi@raspberrypi ~ $ jasper/jasper.py
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playba                                                                                                                     ck stream
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
No disturbance detected
No disturbance detected
INFO:client.stt:Transcribed: ['']
ERROR:apscheduler.executors.default:Job "Notifier.gather (trigger: interval[0:00:30], next run at: 2016-08-23 03:01:50 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 108, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/jasper/client/notifier.py", line 39, in gather
    [client.run() for client in self.notifiers]
  File "/home/pi/jasper/client/notifier.py", line 18, in run
    self.timestamp = self.gather(self.timestamp)
  File "/home/pi/jasper/client/notifier.py", line 43, in handleEmailNotifications
    emails = Gmail.fetchUnreadEmails(self.profile, since=lastDate)
  File "/home/pi/jasper/client/modules/Gmail.py", line 63, in fetchUnreadEmails
    conn.login(profile['gmail_address'], profile['gmail_password'])
  File "/usr/lib/python2.7/imaplib.py", line 505, in login
    typ, dat = self._simple_command('LOGIN', user, self._quote(password))
  File "/usr/lib/python2.7/imaplib.py", line 1062, in _quote
    arg = arg.replace('\\', '\\\\')
AttributeError: 'NoneType' object has no attribute 'replace'
No disturbance detected

```

**Comment by mattcurrycom** [comment]
Looks like your audio is not setup

**Comment by stevenwalton** [comment]
So I had gotten one of the recommended microphones and it worked better. Still has problems with any appreciable distance (more than a foot from the microphone). I'm unsure if it is just not translating or what. I've made recordings using the mic at different distances and I can easily recognize my voice and commands across the room, but Jasper still has a hard time picking them up.

**Comment by mattcurrycom** [comment]
Yeah its likely a tuning/setup issue.  Please take it to the forums and close this, as it is not a code issue.
