### ISSUE TITLE
I just can't get my google speech key to work..

### ISSUE THREAD

**Issue by perskes** [jasperproject/jasper-client#561]
I did everything as recommended on the Guide.
My Key is a ~40 digit number only code, but still I get the error..
I even created an OAuth key, an API Key and a Cloud-API Key, none of them worked.

At least now my pc talks to me: "How can I be on service $NAME?" I guess..

How can I fix this?
(Linux Mint 18)
This is what I get:

```
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
CRITICAL:client.stt:Request failed with http status 403
WARNING:client.stt:Status 403 is probably caused by an invalid Google API key.
CRITICAL:client.stt:Request failed with http status 403
WARNING:client.stt:Status 403 is probably caused by an invalid Google API key.

```

**Comment by perskes** [comment]
BTW: After hitting control+C I get this:

```
^CTraceback (most recent call last):
  File "/home/perskes/jasper/jasper.py", line 151, in <module>
    app.run()
  File "/home/perskes/jasper/jasper.py", line 121, in run
    conversation.handleForever()
  File "/home/perskes/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/perskes/jasper/client/mic.py", line 179, in passiveListen
    transcribed = self.passive_stt_engine.transcribe(f)
  File "/home/perskes/jasper/client/stt.py", line 392, in transcribe
    r = self._http.post(self.request_url, data=data, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt

```

**Comment by G10DRAS** [comment]
You need a "Browser API key" 
key will looks like "XXxxXxXxXxxxXxXxxX_XXXXXXxxxXx_XxxxxxxxX"

**Comment by lockevi** [comment]
Same issue here!

**Comment by apengwin** [comment]
@lockevi  @perskes  i stumbled on this problem as well, but I found that this somehow solved it.

http://bracketsandbraces.blogspot.com/2016/02/google-speech-api-in-c-and-how-to-get.html
