### ISSUE TITLE
Changed jasper name and recompiled keywords

### ISSUE THREAD

**Issue by bwaaaaaa** [jasperproject/jasper-client#569]
I've tried changing JASPER to SAM and used the tool in Jasper's documentation. However after compiling it and replacing the original files. This error came out. 

`ERROR:client.g2p:Command 'phonetisaurus-g2p --model=/home/pi/phonetisaurus/g014b2b.fst --input=/tmp/tmpSq826_.g2p --words --isfile' return with exit status -11
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 271, in _compile_vocabulary
    self._compile_dictionary(vocabulary, self.dictionary_file)
  File "/home/pi/jasper/client/vocabcompiler.py", line 321, in _compile_dictionary
    phonemes = g2pconverter.translate(words)
  File "/home/pi/jasper/client/g2p.py", line 130, in translate
    output = self._translate_words(words)
  File "/home/pi/jasper/client/g2p.py", line 119, in _translate_words
    nbest=self.nbest)
  File "/home/pi/jasper/client/g2p.py", line 56, in execute
    raise OSError("Command execution failed")
OSError: Command execution failed
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 110, in __init__
    stt_engine_class.get_active_instance())
  File "/home/pi/jasper/client/stt.py", line 53, in get_active_instance
    return cls.get_instance('default', phrases)
  File "/home/pi/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
OSError: Command execution failed
`

**Comment by mattcurrycom** [comment]
nothing to recomile... just change the name in jasper.py...

**Comment by kevinzzz007** [comment]
@bwaaaaaa I also have this problem, did you figure out how to solve it?
@mattcurrycom according to https://github.com/jasperproject/jasper-client/issues/8 we need to change the dic files in /jasper/static and also the name in jasper.py...did you only change the name in jasper.py and it worked?  What word did you use?
