### ISSUE TITLE
Jasper not working when Chromium runs in kiosk

### ISSUE THREAD

**Issue by dmahendranme** [jasperproject/jasper-client#570]
I have setup Jasper on Raspberry Pi 3 and made chromium browser to run in kiosk mode on every boot. 
After booting up, I run jasper.py to listen and execute commands.  
But I get this error, 
`Traceback (most recent call last):
  File "jasper/jasper.py", line 151, in <module>
    app.run()
  File "jasper/jasper.py", line 121, in run
    conversation.handleForever()
  File "/home/pi/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/jasper/client/mic.py", line 121, in passiveListen
    data = stream.read(CHUNK)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 605, in read
    return pa.read_stream(self._stream, num_frames)
IOError: [Errno Input overflowed] -9981
`
No error After closing the browser and running jasper.py.

**Comment by mattcurrycom** [comment]
This is an audio error....  does not appear to be related to Chromium, unless its putting a lock on your audio device....
