### ISSUE TITLE
Self.mic and Config = cls.get_config

### ISSUE THREAD

**Issue by Legroking** [jasperproject/jasper-client#571]
Hello everyone,
I have this problem when I  run jasper.py and I don't know how to solve it. 
Please help me and ask me all the information to solve the problem.
Thank a lot,
Vincenzo

pi@raspberrypi:~/jasper $ ./jasper.py
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************

ERROR:root:Error occured!
Traceback (most recent call last):
  File "./jasper.py", line 146, in <module>
    app = Jasper()
  File "./jasper.py", line 108, in __init__
    self.mic = Mic(tts_engine_class.get_instance(),
  File "/home/pi/jasper/client/tts.py", line 57, in get_instance
    config = cls.get_config()
  File "/home/pi/jasper/client/tts.py", line 158, in get_config
    if 'voice' in profile['espeak-tts']:
TypeError: argument of type 'NoneType' is not iterable

**Comment by nadhirlaalai** [comment]
same problem any help pleeeaaaaaaaase
