### ISSUE TITLE
Issues creating profile for jasper 

### ISSUE THREAD

**Issue by abendplays** [jasperproject/jasper-client#574]
Hi guys,
Just tried installing the magic mirror jasper addon and I am getting the following problem, can anyone help me? 
Thank you!! :D 
I used this tutorial https://howchoo.com/g/yti5mmq0ntu/add-v ... ing-jasper tutorial.. 
When I run python /home/pi/jasper/jasper.py I get the error: 
No handlers could be found for logger "cmuclmtk"
*******************************************************
* JASPER - THE TALKING COMPUTER *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
File "/home/pi/jasper/client/vocabcompiler.py", line 163, in compile
self._compile_vocabulary(phrases)
File "/home/pi/jasper/client/vocabcompiler.py", line 269, in _compile_vocabulary
vocabulary = self._compile_languagemodel(text, self.languagemodel_file)
File "/home/pi/jasper/client/vocabcompiler.py", line 290, in _compile_languagemodel
cmuclmtk.text2vocab(text, vocab_file)
NameError: global name 'cmuclmtk' is not defined
ERROR:root:Error occured!
Traceback (most recent call last):
File "/home/pi/jasper/jasper.py", line 146, in <module>
app = Jasper()
File "/home/pi/jasper/jasper.py", line 109, in __init__
stt_passive_engine_class.get_passive_instance(),
File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
return cls.get_instance('keyword', phrases)
File "/home/pi/jasper/client/stt.py", line 40, in get_instance
vocabulary.compile(phrases)
File "/home/pi/jasper/client/vocabcompiler.py", line 171, in compile
raise e
NameError: global name 'cmuclmtk' is not defined

**Comment by mattcurrycom** [comment]
This is not a code issue related to jasper.  Please contact the module creator; or ask in chat.
