### ISSUE TITLE
Ubuntu 16.04 install

### ISSUE THREAD

**Issue by ychoucha** [jasperproject/jasper-client#580]
Hello i have this error : 

```
root@jasper:~/jasper-client/client# python main.py
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ERROR:root:Error occured!
Traceback (most recent call last):
  File "../jasper.py", line 146, in <module>
    app = Jasper()
  File "../jasper.py", line 105, in __init__
    tts_engine_class = tts.get_engine_by_slug(tts_engine_slug)
  File "../client/tts.py", line 665, in get_engine_by_slug
    "missing dependencies, etc.)") % slug)
ValueError: TTS engine 'espeak-tts' is not available (due to missing dependencies, etc.)
```

i m using this script to install Jasper on my frech install of Ubuntu 16.04 :

`sudo apt-get install python-setuptools
sudo easy_install pip
sudo apt-get install python-pocketsphinx python-yaml python-tz python-requests build-essential python-pyaudio
git clone https://github.com/jasperproject/jasper-client.git
#sudo pip install -r jasper-client/client/requirements.txt
sudo pip install APScheduler CherryPy PyYAML Pykka RPi.GPIO argparse beautifulsoup4 facebook-sdk feedparser numpy pifacedigitalio --allow-external pygame python-dateutil python-mpd pytz quantities semantic six ws4py wsgiref requests sphinx
sudo apt-get install python-espeak

cd jasper-client/client
python populate.py
python main.py

#Europe/Paris
#https://jasperproject.github.io/documentation/configuration/`

**Comment by ychoucha** [comment]
ok so now i have a new error : 

```
stagiaire@Jasper:~$ sudo jasper --debug
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
DEBUG:client.diagnose:Checking network connection to server 'www.google.com'...
DEBUG:client.diagnose:Network connection working
DEBUG:__main__:Trying to read config file: '/home/stagiaire/.jasper/profile.yml'
DEBUG:client.diagnose:Checking python import 'pocketsphinx'...
DEBUG:client.diagnose:Python package 'pocketsphinx' found: '/usr/lib/python2.7/dist-packages/pocketsphinx/__init__.py'
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
DEBUG:client.diagnose:Checking executable 'aplay'...
DEBUG:client.diagnose:Executable 'aplay' found: '/usr/bin/aplay'
DEBUG:client.diagnose:Checking executable 'espeak'...
DEBUG:client.diagnose:Executable 'espeak' found: '/usr/bin/espeak'
DEBUG:client.vocabcompiler:compiled_revision is 'bb74ae36d130ef20de710e3a77b43424b8fa774f'
ERROR:client.stt:hmm_dir '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' does not exist! Please make sure that you have set the correct hmm_dir in your profile.
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/usr/local/lib/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/usr/local/lib/jasper/jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/usr/local/lib/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/usr/local/lib/jasper/client/stt.py", line 42, in get_instance
    instance = cls(**config)
  File "/usr/local/lib/jasper/client/stt.py", line 105, in __init__
    raise RuntimeError(msg)
RuntimeError: hmm_dir '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' does not exist! Please make sure that you have set the correct hmm_dir in your profile.
```

what do u think please ?

**Comment by Splitter** [comment]
"RuntimeError: hmm_dir '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' does not exist! Please make sure that you have set the correct hmm_dir in your profile"

Youre hmm_dir is not the default(if you have compiled/installed the dependencies correctly). In your profile.yml you need to define something like this( except pointing to the correct directory for your system)

pocketsphinx:
  hmm_dir: '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k'

**Comment by Mvpchris** [comment]
@Splitter I have the same error 

RuntimeError: hmm_dir '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' does not exist! Please make sure that you have set the correct hmm_dir in your profile.

If it is not the default. How do you find the correct directory for the system?
