### ISSUE TITLE
Jasper help phonetisaurus

### ISSUE THREAD

**Issue by Alex2517** [jasperproject/jasper-client#581]
Hi, I'm a total noob and need help installing Jasper on my Raspberry Pi.

I've tried several walkthroughs, including the one on the Jasper github site, and run into so many problems every time.

I've got to the stage of running jasper, and this(these) errors come up:

*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/Desktop/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/Desktop/jasper/client/vocabcompiler.py", line 271, in _compile_vocabulary
    self._compile_dictionary(vocabulary, self.dictionary_file)
  File "/home/pi/Desktop/jasper/client/vocabcompiler.py", line 320, in _compile_dictionary
    g2pconverter = PhonetisaurusG2P(**PhonetisaurusG2P.get_config())
  File "/home/pi/Desktop/jasper/client/g2p.py", line 93, in __new__
    "instance.") % fst_model)
OSError: FST model ''/home/pi/Desktop/jasper/../phonetisaurus/g014b2b.fst'' does not exist! Can't create instance.
ERROR:root:Error occured!
Traceback (most recent call last):
  File "jasper.py", line 146, in <module>
    app = Jasper()
  File "jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/Desktop/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/Desktop/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/Desktop/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
OSError: FST model ''/home/pi/Desktop/jasper/../phonetisaurus/g014b2b.fst'' does not exist! Can't create instance.

**Comment by Alex2517** [comment]
Sorry, I don't know how you do the fancy boxes with the code in!
Any help would be massively appreciated. This is my 5th attempt now at setting up Jasper.
Thanks for your time guys.

Step by step guidance is very much appreciated, I don't have much knowledge, but really want to learn.

**Comment by Alex2517** [comment]
The file is on the pi somewhere, as I used the "find" command and it showed up, but I don't know where it is and where it needs to be, otherwise I'd try and move it! :)

**Comment by stephanerenouard** [comment]
'Got the same, i'm working on it. Since I have clues, i'll come back.

**Comment by Alex2517** [comment]
Awesome, thanks and good luck!

**Comment by stephanerenouard** [comment]
ok, it's working now. First of all, you have to know that i'm working on a C.H.I.P. board and debian. I follow the tutorial to install Jasper and assume that you did the same. 

I did : 
wget https://www.dropbox.com/s/kfht75czdwucni1/g014b2b.tgz
tar -xvf g014b2b.tgz

Build Phonetisaurus model:

cd g014b2b/
./compile-fst.sh
cd ..

Finally, rename the following folder for convenience:

mv ~/g014b2b ~/phonetisaurus

The last point is not an option !!!! Jasper is looking for this file on the ~/phonetisaurus/ dir. You should move your g014b2b.fst file into this freshly created dir. 

As my config file is pointing elsewhere  (/home/chip/anotherplace../g014b2b.fst), jasper seems to ignore it. 

Maybe I'll have a close look at the source code for this, but moving the file to the required place seems to work (at least, for me).

**Comment by mattcurrycom** [comment]
That is included on my image btw.  Please add any suggestions to the v1.6 image room in slack or the forums.

**Comment by Alex2517** [comment]
Thanks Steph and Matt.

could you help me out with the syntax for the command line.

Where you say to "build the phonetisaurus model" does the change directory command have to have a line break in it like how you have written it?

Also, I get confused when folder paths have /./ or ~/ or /../ etc in them. are these symbols representing additional folder levels? or do you literally type in those dots and wavy lines?

For this reason, it is still not clear to me where Jasper is looking for it

For example, I did place the file into the Jasper folder, but as the path is searching for it here:

 /home/pi/Desktop/jasper/../phonetisaurus/g014b2b.fst

I'm not sure if /../ is a particular folder path? or additional folder levels?

As mentioned, I am a total NOOB so please forgive my novice command line knowledge!

No comment can be too patronising for me, the more idiot-proof the better!

Matt, where might I find your image? (is it a Jasper image, or a Rasbian one?)

**Comment by jngreene** [comment]
The root problem is if you try and use a current github pull of Phonetisaurus (when you discovered the jasper install walkthrough link to the tgz  is a 404 not found) the binary phonetisaurus-g2p is  no longer created by the build process. instead is has phonetisaurus-g2pfst (which does not accept the --input) command line option or seem to have an equivalent and phonetisaurus-g2prnn ... so basically Phonetisaurus changed how they do things and left Jasper in a lurch

**Comment by Alex2517** [comment]
Ah, I see. Yes I did get the 404 and found it elsewhere. So is there a way around it using the new phonenetisaurus biz, or can I get an older build from somewhere?

Thanks for your time and advice :)

**Comment by jngreene** [comment]
I do not yet know.. I'm a troubleshooter by trade.. so I'll find an answer, but have not as yet  determined it. I'll post once I've mapped a resolution to this issue.

**Comment by jngreene** [comment]
Ok update so far. Phonetisaurus 0.8  will not compile against OpenFST 1.4 or newer as OpenFST change a number of things breaking calls relied upon by Phonetisaurus.  The author of Phonetisaurus has done some work on updating, but this necessitated a significant method change resulting in different binaries (multiple binaries to handle different standards) which means that using Jasper as is will require using significantly out of date versions of OpenFST (1.3 or older) and Phonetisaurus (0.8 archive links can be found on https://code.google.com/archive/p/phonetisaurus/ ). I'm fighting the good fight and working on a wrapper to bridge the gap.. I expect some pain as I'm  swimming a bit out of my depth on this, but the author of Phonetisaurus appears to be a very responsive and helpful person, so I have high hopes.

**Comment by Alex2517** [comment]
Awesome. if you're out of your depth, I drowned ages ago haha! 
Good luck with the fight, I'll try and bodge it to work with an older version.

Thanks!

**Comment by ghost** [comment]
Did someone actually resolve the issue here? I really need help with this!

**Comment by G10DRAS** [comment]
Lets try this pkg:
https://github.com/G10DRAS/Raspbian-Pkgs/blob/master/phonetisaurus-_0.8-1_armhf.deb

sudo dpkg -i phonetisaurus-_0.8-1_armhf.deb

**Comment by lucaskapobassis** [comment]
I just used this website to download it and do the bit where he says instead of:
[](http://chrismeiercs.com/blog/2016/02/27/installing-jasper-on-raspberry-pi-b-plus/ )

**Comment by lucaskapobassis** [comment]
http://chrismeiercs.com/blog/2016/02/27/installing-jasper-on-raspberry-pi-b-plus/

**Comment by Alex2517** [comment]
Thanks Z, I'll give that approach a go :)
