### ISSUE TITLE
IOError: [Errno Invalid sample rate] -9997 I      is the error im getting

### ISSUE THREAD

**Issue by leearthur56** [jasperproject/jasper-client#595]
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
  File "jasper/jasper.py", line 151, in <module>
    app.run()
  File "jasper/jasper.py", line 121, in run
    conversation.handleForever()
  File "/home/pi/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/jasper/client/mic.py", line 110, in passiveListen
    frames_per_buffer=CHUNK)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 747, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 442, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno Invalid sample rate] -9997

**Comment by ashishmusale** [comment]
I am having the same problem. Did you find the solution?

**Comment by leearthur56** [comment]
no i have not :(

**Comment by G10DRAS** [comment]
why not you try below in ~/.asoundrc file. 
check which one is your USB Card and replace card value (card 0) accordingly.
do the same for internal sound card.
```

pcm.usb
{
    type hw
    card 0
}

pcm.internal
{
    type hw
    card 1
}

pcm.!default
{
    type asym
    playback.pcm
    {
        type plug
        slave.pcm "internal"
    }
    capture.pcm
    {
        type plug
        slave.pcm "usb"
    }
}

ctl.!default
{
    type asym
    playback.pcm
    {
        type plug
        slave.pcm "internal"
    }
    capture.pcm
    {
        type plug
        slave.pcm "usb"
    }
}
```

**Comment by ashishmusale** [comment]
@ArthurLee1 I finally got it working last night. I had to change the RATE in the mic.py. Once I fixed that I started getting overflow error then I had to go in and change the CHUNK size.

I set the RATE to 48000 and chunk to 8132. Now its listening but it doesn't detect voice much. I am going to try the dev branch to see if that improves anything

**Comment by flipchan** [comment]
hi i also got this error and changed it like u did @ashishmusale  and got a overflow error 
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_equal.c:196:(_snd_pcm_equal_open) No slave configuration for equal pcm
ALSA lib pcm_equal.c:196:(_snd_pcm_equal_open) No slave configuration for equal pcm
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
WARNING:client.notifier:gmail_address or gmail_password not set in profile, Gmail notifier will not be used
Traceback (most recent call last):
  File "jasper.py", line 151, in <module>
    app.run()
  File "jasper.py", line 121, in run
    conversation.handleForever()
  File "/root/gits/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/root/gits/jasper/client/mic.py", line 121, in passiveListen
    data = stream.read(CHUNK)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 605, in read
    return pa.read_stream(self._stream, num_frames)
IOError: [Errno Input overflowed] -9981
INFO: ngram_search_fwdtree.c(429): TOTAL fwdtree 0.00 CPU nan xRT
INFO: ngram_search_fwdtree.c(432): TOTAL fwdtree 0.00 wall nan xRT
INFO: ngram_search_fwdflat.c(176): TOTAL fwdflat 0.00 CPU nan xRT
INFO: ngram_search_fwdflat.c(179): TOTAL fwdflat 0.00 wall nan xRT
INFO: ngram_search.c(303): TOTAL bestpath 0.00 CPU nan xRT
INFO: ngram_search.c(306): TOTAL bestpath 0.00 wall nan xRT
INFO: ngram_search_fwdtree.c(429): TOTAL fwdtree 0.00 CPU nan xRT
INFO: ngram_search_fwdtree.c(432): TOTAL fwdtree 0.00 wall nan xRT
INFO: ngram_search_fwdflat.c(176): TOTAL fwdflat 0.00 CPU nan xRT
INFO: ngram_search_fwdflat.c(179): TOTAL fwdflat 0.00 wall nan xRT
INFO: ngram_search.c(303): TOTAL bestpath 0.00 CPU nan xRT
INFO: ngram_search.c(306): TOTAL bestpath 0.00 wall nan xRT

i changed it like u did but i still get the same error 
 89     def passiveListen(self, PERSONA):
 90         """
 91         Listens for PERSONA in everyday sound. Times out after LISTEN_TIME,     so
 92         needs to be restarted.
 93         """
 94 
 95         THRESHOLD_MULTIPLIER = 1.8
 96         RATE = 48000
 97         CHUNK = 8132
 98

**Comment by ashishmusale** [comment]
sorry, my bad. The chunk value is 8192

**Comment by flipchan** [comment]
@ashishmusale  did u change all        RATE = 16000   CHUNK = 1024 in mic.py?

**Comment by flipchan** [comment]
i think i need some other value if i use 8192 and get:
No disturbance detected
No disturbance detected
No disturbance detected

and when i use 4096 i get the same error

**Comment by flipchan** [comment]
Cannot connect to server request channel
jack server is not running or cannot be started
WARNING:client.notifier:gmail_address or gmail_password not set in profile, Gmail notifier will not be used
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
  File "jasper.py", line 151, in <module>
    app.run()
  File "jasper.py", line 121, in run
    conversation.handleForever()
  File "/root/gits/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/root/gits/jasper/client/mic.py", line 110, in passiveListen
    frames_per_buffer=CHUNK)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 747, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 442, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno Invalid sample rate] -9997
INFO: ngram_search_fwdtree.c(429): TOTAL fwdtree 0.00 CPU nan xRT
INFO: ngram_search_fwdtree.c(432): TOTAL fwdtree 0.00 wall nan xRT
INFO: ngram_search_fwdflat.c(176): TOTAL fwdflat 0.00 CPU nan xRT
INFO: ngram_search_fwdflat.c(179): TOTAL fwdflat 0.00 wall nan xRT
INFO: ngram_search.c(303): TOTAL bestpath 0.00 CPU nan xRT
INFO: ngram_search.c(306): TOTAL bestpath 0.00 wall nan xRT
INFO: ngram_search_fwdtree.c(429): TOTAL fwdtree 0.00 CPU nan xRT
INFO: ngram_search_fwdtree.c(432): TOTAL fwdtree 0.00 wall nan xRT
INFO: ngram_search_fwdflat.c(176): TOTAL fwdflat 0.00 CPU nan xRT
INFO: ngram_search_fwdflat.c(179): TOTAL fwdflat 0.00 wall nan xRT
INFO: ngram_search.c(303): TOTAL bestpath 0.00 CPU nan xRT
INFO: ngram_search.c(306): TOTAL bestpath 0.00 wall nan xRT
root@raspberrypi:~/gits/jasper#

**Comment by ashishmusale** [comment]
@flipchan Yes, I changed all the instances of RATE and CHUNK

**Comment by flipchan** [comment]
@ashishmusale  seem like some kind of wierd error i have tried 

42000 #36000 #24000 #48000 #16000
7168 #6144 #5120 #4096 #8192 #1024

and IOError: [Errno Invalid sample rate] -9997

**Comment by leearthur56** [comment]
Hi, I also changed all the RATE's and CHUNK's, but it still doesn't work and I am getting this weird message:
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Traceback (most recent call last):
  File "jasper/jasper.py", line 151, in <module>
    app.run()
  File "jasper/jasper.py", line 121, in run
    conversation.handleForever()
  File "/home/pi/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/jasper/client/mic.py", line 183, in passiveListen
    transcribed = self.passive_stt_engine.transcribe(f)
  File "/home/pi/jasper/client/stt.py", line 392, in transcribe
    r = self._http.post(self.request_url, data=data, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(32, 'Broken pipe'))






Thanks all for helping!

**Comment by mzlarsson** [comment]
Hi!
If your mic doesn't support a sample rate of 16kHz (which seems to be the case in this issue thread) you can fix it by doing some edits in mic.py:
1. First off, change all the `RATE` variables to one that your mic does support
2. Secondly, increase the `CHUNK` variable in the magnitude in order to make up for the increase in data size. In my case I increased the sample rate from 16000Hz to 44100Hz, so I also increased the chunk size from 1024 to 3072 (since around 3 times more data is generated). For simple usage, one could use the formula `(NEW_SAMPLE_RATE/16000) * 1024` to get a rough estimate.
3. When arriving to this third step, no errors should occur but Jasper will be quite unable to understand what you are trying to say. This is because the samples from the mic are compared with 16kHz preset samples in order to get what you are saying. Since we changed the sample rate, the comparison will therefore be quite inaccurate. In order to fix this, we need to resample all mic input before using it. I wrote a small code part for doing this:
```
def resample(self, data, rate):
    (newfragment, state) = audioop.ratecv(data, 2, 1, rate, 16000, None)
    return newfragment
```
Change so that you always call this function when you read the data, i.e. change all lines with
`data = stream.read(CHUNK)`
to
`data = self.resample(stream.read(CHUNK), RATE)`

This should do the trick! If I have the time I will try to generalize this part and make a pull request, but in the meantime I hope this help you.

**Comment by presingjos** [comment]
#### THANK YOU!
This worked perfectly!
I was using [this microphone](https://www.amazon.com/Kinobo-Microphone-Desktop-Recognition-Software/dp/B00IR8R7WQ/ref=sr_1_4?ie=UTF8&qid=1517188236&sr=8-4&keywords=usb+2.0+microphone) from amazon

**Comment by leearthur56** [comment]
No problem!
