### ISSUE TITLE
Jasper issues | January 2017

### ISSUE THREAD

**Issue by rizwhiz1** [jasperproject/jasper-client#596]
Installed all updates and dependencies as provided in  Jasper documentation and google forums for my Raspberry pi, but i got following errors.

*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 91, in __init__
    stt_engine_class = stt.get_engine_by_slug(stt_engine_slug)
  File "/home/pi/jasper/client/stt.py", line 648, in get_engine_by_slug
    "dependencies, etc.)") % slug)
ValueError: STT engine 'sphinx' is not available (due to missing dependencies, missing dependencies, etc.)

The phonetisaurus dependency was installed from following command.

wget https://www.dropbox.com/s/1bgavg07qx8fe5w/phonetisaurus-googlecode-archive.tgz?dl=0
tar xzf phonetisaurus-googlecode-archive.tgz?dl=0
cd phonetisaurus-googlecode-archive/downloads
tar xzf phonetisaurus-0.7.8.tgz
cd phonetisaurus-0.7.8/src
sudo make

The Python Pip bug was solved with these commands.
$ sudo apt-get purge -y python-pip
$ sudo easy_install pip

still unable to locate problems
Kindly help me to tackle the errors occurred while running Jasper.

**Comment by G10DRAS** [comment]
Try to install all Pocketsphinx dependencies manually. Don't use experimental repository.

**Comment by syphr42** [comment]
I built a Docker image for Jasper that I have running successfully on RPi 3. You can use that directly or follow it as a guide to getting Jasper and it's dependencies up and running on your Pi. It uses PocketSphinx and Pico (no cloud services). 

https://hub.docker.com/r/syphr/jasper
https://github.com/syphr42/docker-jasper
