### ISSUE TITLE
Jasper --diagnose: 'say' is missing in $PATH

### ISSUE THREAD

**Issue by aallard** [jasperproject/jasper-client#598]
I have Jasper setup and mostly working on my RPi3.  The problem I'm encountering is that when I start Jasper ($ python jasper.py) it launches and says "How can I be of service, Adam?"  I then say "Jasper" and the system gives two high beeps and then immediately two low beeps.  After a couple of seconds of silence, Jasper then says "Pardon" (I think).  

The system does recognize that I said "Jasper" but doesn't seem to be able to do anything beyond that.

I ran "$ python jasper.py --diagnose" and this was the output:

*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
INFO:client.diagnose:Starting jasper diagnostic at Thu Feb 16 12:55:45 2017
INFO:client.diagnose:Git revision: '85accbb30a2bc97995ab7991d71941885b848cfa'
WARNING:client.diagnose:Executable 'say' is missing in $PATH
Traceback (most recent call last):
  File "jasper.py", line 142, in <module>
    failed_checks = diagnose.run()
  File "/home/pi/jasper-client/client/diagnose.py", line 163, in run
    for req in get_pip_requirements():
  File "/home/pi/jasper-client/client/diagnose.py", line 107, in get_pip_requirements
    reqs = list(pip.req.parse_requirements(fname))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_file.py", line 79, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session'

Any ideas?

**Comment by simon1tan** [comment]
I think you may be missing some pip packages although it doesn't say which one. Perhaps look through http://jasperproject.github.io/documentation/installation/ and see if you missed a step. Also, in your terminal, type in:
pip list

Copy and paste here.

**Comment by techticmitwa** [comment]
i have the same error as above and this is what my pip list looks like: 

`DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appdirs (1.4.2)
APScheduler (3.0.1)
beautifulsoup4 (4.3.2)
blinker (1.3)
chardet (2.3.0)
cmuclmtk (0.1.5)
colorama (0.3.2)
distribute (0.7.3)
facebook-sdk (0.4.0)
feedparser (5.1.3)
Flask (0.10.1)
futures (3.0.5)
gpiozero (1.3.1)
gyp (0.1)
html5lib (0.999)
itsdangerous (0.24)
Jinja2 (2.7.3)
lxkeymap (0.1)
MarkupSafe (0.23)
mcpi (0.1.1)
mock (1.0.1)
MySQL-python (1.2.3)
ndg-httpsclient (0.3.2)
numpy (1.12.0)
packaging (16.8)
picamera (1.12)
picraft (1.0)
pifacecommon (4.2.1)
pifacedigitalio (3.1.0)
pigpio (1.30)
Pillow (2.6.1)
pip (9.0.1)
PocketSphinx (0.8)
pyasn1 (0.1.7)
PyAudio (0.2.10)
pygame (1.9.2a0)
pygobject (3.14.0)
pyinotify (0.9.4)
pyOpenSSL (0.13.1)
pyparsing (2.1.10)
pyserial (2.6)
python-apt (0.9.3.12)
python-dateutil (2.3)
python-mpd (0.3.0)
pytz (2014.10)
PyYAML (3.11)
quantities (0-unknown)
requests (2.5.0)
RPi.GPIO (0.6.3)
RTIMULib (7.2.1)
semantic (1.0.3)
sense-emu (1.0)
sense-hat (2.2.0)
setuptools (34.3.1)
six (1.10.0)
smbus (1.1)
SphinxBase (0.8)
spidev (3.0)
twython (3.1.2)
tzlocal (1.3)
urllib3 (1.9.1)
Werkzeug (0.9.6)
wheel (0.24.0)
`

**Comment by bartfeenstra** [comment]
`say` is a Mac OS built-in command. You'll need to use another [TTS solution](http://jasperproject.github.io/documentation/configuration/#tts) on Linux.
