### ISSUE TITLE
Cant play spotify playlists

### ISSUE THREAD

**Issue by chill07** [jasperproject/jasper-client#603]
i keep getting this error
He fails to load the playlist as he says "I'm sorry, I'm having some trouble with that operation"
There's this, if it's of any help
ERROR:client.brain:Failed to execute module
Traceback (most recent call last):
File "/home/pi/jasper/client/brain.py", line 67, in query
module.handle(text, self.mic, self.profile)
File "/home/pi/jasper/client/modules/MPDControl.py", line 47, in handle
music_mode.handleForever()
File "/home/pi/jasper/client/modules/MPDControl.py", line 175, in handleForever
self.mic.say("Playing %s" % self.music.current_song())
File "/home/pi/jasper/client/modules/MPDControl.py", line 218, in wrap
return func(self, _default_args, *_default_kwargs)
File "/home/pi/jasper/client/modules/MPDControl.py", line 296, in current_song
item = self.client.playlistinfo(int(self.client.status()["song"]))[0]
KeyError: 'song'

i have tried reinstalling but to no avail. i am using raspbian jessie lite.
i already run my mopidy as a service. here is it's status
![17475244_1307115319324007_906910683_o](https://cloud.githubusercontent.com/assets/26640852/24278786/e09c4d8e-1080-11e7-94a7-89df2fd5fcf1.jpg)

please help me guys ! i cant seem to find where i went wrong

**Comment by Nikozi93** [comment]
I wish there was an answer to that question :( I'm having the same issue...
