### ISSUE TITLE
ValueError: TTS engine 'festival-tts' is not available (due to missing dependencies, etc.)

### ISSUE THREAD

**Issue by ghost** [jasperproject/jasper-client#615]
I get the same for eSpeak, but both are installed :( (tried to install festival-tts as a workaround when it gave me same message for eSpeak)

Installed it on archlinux... there is no path to be configured for tts engines. How to proceed?

```
$ jasper-voice-control
*******************************************************                                      
*             JASPER - THE TALKING COMPUTER           *                                      
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *                                      
*******************************************************                                      
ERROR:root:Error occured!                                                                    
Traceback (most recent call last):                                                           
  File "/usr/share/jasper-voice-control/jasper.py", line 146, in <module>                    
    app = Jasper()                                                                           
  File "/usr/share/jasper-voice-control/jasper.py", line 105, in __init__                    
    tts_engine_class = tts.get_engine_by_slug(tts_engine_slug)                               
  File "/usr/share/jasper-voice-control/client/tts.py", line 665, in get_engine_by_slug      
    "missing dependencies, etc.)") % slug)                                                   
ValueError: TTS engine 'festival-tts' is not available (due to missing dependencies, etc.)
```

profile.yml

```
stt_engine: sphinx                                                                           
#tts_engine: espeak-tts                                                                      
tts_engine: festival-tts                                                                     
                                                                                             
#espeak-tts:                                                                                 
# voice: 'default+m3'   # optional                                                           
# pitch_adjustment: 40  # optional                                                           
# words_per_minute: 160 # optional                                                           
                                                                                             
pocketsphinx:                                                                                
    hmm_dir: '/usr/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k'                         
    fst_model: '/usr/share/phonetisaurus/scripts/g014b2b/g014b2b.fst'
```

**Comment by a-andre** [comment]
It looks like _aplay_ is missing. Installing alsa-utils should fix the issue.
