### ISSUE TITLE
ImportError: libpocketsphinx.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bhodgs01** [jasperproject/jasper-client#62]
hello,

I just installed the jasper image and am getting the above error.  I tried reinstalling the pocketsphinx twice and am still getting the same error.  I saw that someone else was having the same problem on another forum but didn't see an answer.  please help.  I have the log of the install but nothing out of the ordinary seems to be going on.  

I get 

:~/git/jasper-client/client$ python main.py 
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from conversation import Conversation
  File "/home/patrick/git/jasper-client/client/conversation.py", line 2, in <module>
    from musicmode import *
  File "/home/patrick/git/jasper-client/client/musicmode.py", line 6, in <module>
    from mic import Mic
  File "/home/patrick/git/jasper-client/client/mic.py", line 17, in <module>
    import pocketsphinx as ps
ImportError: libpocketsphinx.so.1: cannot open shared object file: No such file or directory

**Comment by lowdev** [comment]
"sudo ldconfig" did the job for me!
