### ISSUE TITLE
RuntimeError: hmm_dir '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' does not exist! Please make sure that you have set the correct hmm_dir in your profile

### ISSUE THREAD

**Issue by estelaromero** [jasperproject/jasper-client#625]
Hello, I am following Jasper documentation to setup client properly and right now I am here: http://jasperproject.github.io/documentation/configuration/#pocketsphinx-stt

Problem is I cannot find hmm directory neither here or in any other location
/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k

I don't even have a folder pocketsphinx under /usr/local/share

fst model could be found though.

I am very newbie and I don't know how to find the cause for this missing folder. Anyone could help?

**Comment by estelaromero** [comment]
Due to this I get an error when running jasper:
ERROR:client.stt:hmm_dir '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' does not exist! Please make sure that you have set the correct hmm_dir in your profile.
ERROR:root:Error occured!
Traceback (most recent call last):
  File "jasper.py", line 146, in <module>
    app = Jasper()
  File "jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 42, in get_instance
    instance = cls(**config)
  File "/home/pi/jasper/client/stt.py", line 105, in __init__
    raise RuntimeError(msg)
RuntimeError: hmm_dir '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' does not exist! Please make sure that you have set the correct hmm_dir in your profile

Anyone could help me find out where to get this model? Thanks

**Comment by absentdream** [comment]
i hit same error and found it might be due to a pocketsphinx version update (ubuntu 17.04)
set the variable in config file 
`
pocketsphinx:
  hmm_dir: '/usr/share/pocketsphinx/model/'

`

but also had to change the loading of the decoder asper-client/client/stt.py around line 125 to

`
        config = ps.Decoder.default_config()
        config.set_string('-hmm', os.path.join(hmm_dir, 'en-us/en-us'))
        config.set_string('-lm', os.path.join(hmm_dir, 'en-us/en-us.lm.bin'))
        config.set_string('-dict', os.path.join(hmm_dir, 'en-us/cmudict-en-us.dict'))

        self._decoder = ps.Decoder(config)
`

not sure if this helps as hitting other errors..  bit clunky install on 17.0.4 :)

**Comment by combs** [comment]
I can't figure out where these model files should come from. The format expected doesn't seem to match what's in the pocketsphinx-0.8 codebase. 

pocketsphinx-0.8:
`model/hmm/en_US/hub4wsj_sc_8k/mdef` 

output from jasper modified per @absentdream:
```
ERROR: "acmod.c", line 83: Folder '/usr/share/pocketsphinx/model/en-us/en-us' does not contain acoustic model definition 'mdef'
```
(ps @absentdream you can do multi-line code blocks in markdown with three ``` on their own line with a \n before and after)

**Comment by galamdring** [comment]
If you are installing this on a debian variant (such as Raspbian) you need the additional package pocketsphinx-en-us. The model files are installed in `/usr/share/pocketsphinx/model/en-us/en-us/`

**Comment by DonHege** [comment]
Thanks for pointing this out. It solved the issue for me, but it's not in the installation instructions as far as I can see.
