### ISSUE TITLE
Error when starting Jasper - ImportError: cannot import name IncompleteRead

### ISSUE THREAD

**Issue by estelaromero** [jasperproject/jasper-client#626]
Hi, 

I am trying to start jasper.py and I am getting the following error

**pi@raspberrypi:~/jasper $ python jasper.py
Traceback (most recent call last):
  File "jasper.py", line 12, in <module>
    from client import tts
  File "/home/pi/jasper/client/tts.py", line 41, in <module>
    import diagnose
  File "/home/pi/jasper/client/diagnose.py", line 9, in <module>
    import pip.req
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead**

Anyone could give a hint about what's wrong and how to fix it? Thanks!

**Comment by estelaromero** [comment]
I fixed it by upgrading pip.  Closing.
