### ISSUE TITLE
Missing VoxForge.tgz with Julius

### ISSUE THREAD

**Issue by combs** [jasperproject/jasper-client#633]
When I try to run Jasper with the Julius STT engine, it crashes because of a missing VoxForge.tgz file. I can't find this in the Jasper repo. Any tips?

```
combs@pinebook:/usr/share/pocketsphinx$ ~/git/jasper/jasper.py
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/combs/git/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/combs/git/jasper/client/vocabcompiler.py", line 436, in _compile_vocabulary
    lexicon_archive_member)
  File "/home/combs/git/jasper/client/vocabcompiler.py", line 338, in __init__
    self.parse(fname, membername)
  File "/home/combs/git/jasper/client/vocabcompiler.py", line 356, in parse
    with self.open_dict(fname, membername=membername) as f:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/combs/git/jasper/client/vocabcompiler.py", line 342, in open_dict
    if tarfile.is_tarfile(fname):
  File "/usr/lib/python2.7/tarfile.py", line 2622, in is_tarfile
    t = open(name)
  File "/usr/lib/python2.7/tarfile.py", line 1673, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1738, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/usr/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/home/combs/git/jasper/static/julius-stt/VoxForge.tgz'
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/combs/git/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/home/combs/git/jasper/jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/combs/git/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/combs/git/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/combs/git/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
IOError: [Errno 2] No such file or directory: '/home/combs/git/jasper/static/julius-stt/VoxForge.tgz'
```

**Comment by G10DRAS** [comment]
well download it from 
https://github.com/G10DRAS/German-G2P-and-Acoustic-Model/blob/master/voxforge-de-r20141117.tar.gz

**Comment by G10DRAS** [comment]
Download it from 
http://www.repository.voxforge1.org/downloads/SpeechCorpus/Trunk/Lexicon/VoxForge.tgz
