### ISSUE TITLE
jasper Ubuntu 17.04 Python 3.5.2

### ISSUE THREAD

**Issue by sekarpdkt** [jasperproject/jasper-client#638]
hi

does anyone have success in using Jasper in Ubuntu 17.04, Python 3.5.2? my setup
$ uname -a
Linux sekar-J1900NH2 4.10.0-32-generic #36-Ubuntu SMP Tue Aug 8 12:10:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ python --version
Python 3.5.2 :: Anaconda 4.2.0 (64-bit)
$ pip --version
pip 9.0.1 from /home/sekar/anaconda3/lib/python3.5/site-packages (python 3.5)

Issues i fixed.
1. in tty.py, 4L was not accepted and I changed it to 32 for fixing
/jasper/client/tts.py", line 103
    wav.setsampwidth(4L)
                      ^
SyntaxError: invalid syntax
2. in populate.py, raw_input() changed to input() for fixing
File "populate.py", line 19, in simple_request
    input = raw_input(cleanVar + ": ")
NameError: name 'raw_input' is not defined

3. in populate.py, input is a variable as well as function. So changed input varaiable name to inputr for fixing
File "populate.py", line 19, in simple_request
    input = input(cleanVar + ": ")
UnboundLocalError: local variable 'input' referenced before assignment

4. File "populate.py", line 114, in run
    "to PocketSphinx): " % stt_engines.keys())
was fixed by changing to {0} and .format()

5. urlpare changed to urllib.parse for fixing
/jasper/client/tts.py", line 19, in <module>
    import urlparse
ImportError: No module named 'urlparse'

Now struck with this when i try python jasper.py

/jasper/client/tts.py", line 41, in <module>
    import diagnose
ImportError: No module named 'diagnose'

**Comment by sekarpdkt** [comment]
I tried to install python2.7 and ran 

$python2.7 jasper.py

but getting this error now

$ python2.7 jasper.py 
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:root:Error occured!
Traceback (most recent call last):
  File "jasper.py", line 146, in <module>
    app = Jasper()
  File "jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/sekar/speechrecognition/jasper/jasperOrg/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/sekar/speechrecognition/jasper/jasperOrg/client/stt.py", line 42, in get_instance
    instance = cls(**config)
  File "/home/sekar/speechrecognition/jasper/jasperOrg/client/stt.py", line 90, in __init__
    import pocketsphinx as ps
  File "/usr/lib/python2.7/dist-packages/pocketsphinx/__init__.py", line 37, in <module>
    from pocketsphinx import *
  File "/usr/lib/python2.7/dist-packages/pocketsphinx/pocketsphinx.py", line 42, in <module>
    _pocketsphinx = swig_import_helper()
  File "/usr/lib/pythImportError: /usr/lib/x86_64-linux-gnu/libpocketsphinx.so.3: undefined symbol: err_set_debug_level
Exception AttributeError: "'PocketSphinxSTT' object has no attribute '_logfile'" in <bound method PocketSphinxSTT.__del__ of <client.stt.PocketSphinxSTT object at 0x7f7e99678d10>> ignored

on2.7/dist-packages/pocketsphinx/pocketsphinx.py", line 38, in swig_import_helper
    _mod = imp.load_module('_pocketsphinx', fp, pathname, description)
ImportError: /usr/lib/x86_64-linux-gnu/libpocketsphinx.so.3: undefined symbol: err_set_debug_level
Exception AttributeError: "'PocketSphinxSTT' object has no attribute '_logfile'" in <bound method PocketSphinxSTT.__del__ of <client.stt.PocketSphinxSTT object at 0x7f7e99678d10>> ignored

**Comment by zoecarver** [comment]
This seems to be an issue with pocket sphinx. I recommend you try a different STT engine. I have had success with Watson and Wit.ai.

**Comment by Rawan19** [comment]
from client import diagnose fixes it
