### ISSUE TITLE
error while doing python main.py

### ISSUE THREAD

**Issue by kucinkperang** [jasperproject/jasper-client#647]
hello

i'm getting an error while doing python main.py

`Traceback (most recent call last):
  File "main.py", line 10, in <module>
    runpy.run_path(script_path, run_name="__main__")
  File "/usr/lib/python2.7/runpy.py", line 252, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "../jasper.py", line 12, in <module>
    from client import tts
  File "../client/tts.py", line 41, in <module>
    import diagnose
  File "../client/diagnose.py", line 9, in <module>
    import pip.req
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning
`
any help would be appreciated

thank you

**Comment by webberd1wei** [comment]
I followed this: https://github.com/infobyte/faraday/issues/164
