### ISSUE TITLE
INFO:client.stt:Transcribed: [u'JASPER'] CRITICAL:client.stt:Request failed with response: u'{\n  "error" : "Bad request",\n  "code" : "bad-request"\n}' Traceback (most recent call last):   File "/home/pi/jasper/client/stt.py", line 594, in transcribe     r.raise_for_status()   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 829, in raise_for_status     raise HTTPError(http_error_msg, response=self) HTTPError: 400 Client Error: Bad Request CRITICAL:client.stt:Request failed with response: u'{\n  "error" : "Bad request",\n  "code" : "bad-request"\n}' Traceback (most recent call last):   File "/home/pi/jasper/client/stt.py", line 594, in transcribe     r.raise_for_status()   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 829, in raise_for_status     raise HTTPError(http_error_msg, response=self) HTTPError: 400 Client Error: Bad Request

### ISSUE THREAD

**Issue by YouEatCheese** [jasperproject/jasper-client#655]
Can´t hear t beeps...

INFO:client.conversation:Nothing has been said or transcribed.
DEBUG:client.conversation:Started listening for keyword 'JASPER'
 INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.wit.ai
DEBUG:requests.packages.urllib3.connectionpool:"POST /speech?v=20150101 HTTP/1.1" 200 215
INFO:client.stt:Transcribed: [u'JASPER']
DEBUG:client.conversation:Stopped listening for keyword 'JASPER'
INFO:client.conversation:Keyword 'JASPER' has been said!
DEBUG:client.conversation:Started to listen actively with threshold: 25.2
DEBUG:client.tts:Executing aplay -D plughw:1,0 /home/pi/jasper/static/audio/beep_hi.wav
DEBUG:client.tts:Output was: 'Playing WAVE '/home/pi/jasper/static/audio/beep_hi.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
'
DEBUG:client.tts:Executing aplay -D plughw:1,0 /home/pi/jasper/static/audio/beep_lo.wav
DEBUG:client.tts:Output was: 'Playing WAVE '/home/pi/jasper/static/audio/beep_lo.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
'
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.wit.ai
DEBUG:requests.packages.urllib3.connectionpool:"POST /speech?v=20150101 HTTP/1.1" 400 55
CRITICAL:client.stt:Request failed with response: u'{\n  "error" : "Bad request",\n  "code" : "bad-request"\n}'
Traceback (most recent call last):
  File "/home/pi/jasper/client/stt.py", line 594, in transcribe
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 829, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 400 Client Error: Bad Request

**Comment by aaronfranco** [comment]
The title of this Issue is incredibly difficult to understand. The core issue is that the WIT.ai API is out of date in this client library. 

1. the 2015 API version is out of date.
2. The client sends audio/raw without proper headers
