### ISSUE TITLE
Errors at first start up with jasper.py

### ISSUE THREAD

**Issue by s1nu5** [jasperproject/jasper-client#658]
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 79, in __init__
    with open(new_configfile, "r") as f:
IOError: [Errno 2] No such file or directory: '/root/.jasper/profile.yml'

These are the errors I get, after I type sudo /home/pi/jasper/jasper.py.
I'm new to the Raspi, so maybe I'm just doing something fundamentally wrong, but I've got it figured out till here. It would be very nice, if someone could explan to me what's wrong with the two files.

I particularly don't understand 

> IOError: [Errno 2] No such file or directory: '/root/.jasper/profile.yml'

because that file is in the .jasper directory.

Hope anybody can help me out over here.

**Comment by G10DRAS** [comment]
run the script without `sudo`
