### ISSUE TITLE
KeyError: 'song' at MPDControl.py

### ISSUE THREAD

**Issue by Niss95** [jasperproject/jasper-client#660]
I have an error with the MPDControl.py after Jasper tries to run spotify.
These are my errors:

ERROR:client.brain:Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 73, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/MPDControl.py", line 47, in handle
    music_mode.handleForever()
  File "/home/pi/jasper/client/modules/MPDControl.py", line 160, in handleForever
    self.mic.say("Playing %s" % self.music.current_song())
  File "/home/pi/jasper/client/modules/MPDControl.py", line 204, in wrap
    return func(self, *default_args, **default_kwargs)
  File "/home/pi/jasper/client/modules/MPDControl.py", line 283, in current_song
    item = self.client.playlistinfo(int(self.client.status()["song"]))[0]
KeyError: 'song'

I saw that the MPDControl.py is rewritten at jasper-dev

**Comment by G10DRAS** [comment]
Which version of MPD and MPC are you using ?

**Comment by Nikozi93** [comment]
Did you manage to solve it? If so, could you please share how you did it?
