### ISSUE TITLE
when i try to run ./jasper.py i got a error

### ISSUE THREAD

**Issue by cybermritunjay** [jasperproject/jasper-client#666]
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/flux/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/flux/jasper/client/vocabcompiler.py", line 271, in _compile_vocabulary
    self._compile_dictionary(vocabulary, self.dictionary_file)
  File "/home/flux/jasper/client/vocabcompiler.py", line 320, in _compile_dictionary
    g2pconverter = PhonetisaurusG2P(**PhonetisaurusG2P.get_config())
  File "/home/flux/jasper/client/g2p.py", line 90, in __new__
    "$PATH.")
OSError: Can't find command 'phonetisaurus-g2p'! Please check if Phonetisaurus is installed and in your $PATH.
ERROR:root:Error occured!
Traceback (most recent call last):
  File "./jasper.py", line 146, in <module>
    app = Jasper()
  File "./jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/flux/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/flux/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/flux/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
OSError: Can't find command 'phonetisaurus-g2p'! Please check if Phonetisaurus is installed and in your $PATH

**Comment by G10DRAS** [comment]
Error explain itself:

`OSError: Can't find command 'phonetisaurus-g2p'! Please check if Phonetisaurus is installed and in your $PATH.`
