### ISSUE TITLE
Issue launching Jasper

### ISSUE THREAD

**Issue by powbabix** [jasperproject/jasper-client#676]
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 12, in <module>
    from client import tts
  File "/home/pi/jasper/client/tts.py", line 41, in <module>
    import diagnose
  File "/home/pi/jasper/client/diagnose.py", line 9, in <module>
    import pip.req
ImportError: No module named req

Error I get when running Jasper. Unsure as to what the cause is. Any help would be appreciated. Apologies if incorrect place if anyone could guide me elsewhere even. Thanks 

 
OS is raspbien Jessie with MagicMirror installed.

**Comment by G10DRAS** [comment]
install pip

https://pip.pypa.io/en/stable/installing/#installation

**Comment by ahmadasadi** [comment]
pi@raspberry:~ $ pip install -U pip
Looking in indexes: https://pypi.python.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages/pip-10.0.0b2-py2.7.egg (10.0.0b2)
pi@raspberry:~ $ jasper/jasper.py
Traceback (most recent call last):
  File "jasper/jasper.py", line 12, in <module>
    from client import tts
  File "/home/pi/jasper/client/tts.py", line 41, in <module>
    import diagnose
  File "/home/pi/jasper/client/diagnose.py", line 9, in <module>
    import pip.req
ImportError: No module named req
==========================
i install pip again but i have the same problem.
what should i do?
my profile is this :
carrier: ''
first_name: ahmad
gmail_password: ''
last_name: asadi
location: Toronto
phone_number: ''
prefers_email: true
timezone: America/Toronto
stt_engine:witai
witai-stt:
  access_token:.........(i hidden it)
tts_engine:google-tts
-------------
i used google gTTS and witai stt   as in the youtube tutorial
----------------

thanks a lot

**Comment by G10DRAS** [comment]
try
sudo python -m pip install --upgrade pip==9.0.3
