### ISSUE TITLE
hi i have problem when run jasper.py as is:

### ISSUE THREAD

**Issue by ahmadasadi** [jasperproject/jasper-client#677]

**Comment by ahmadasadi** [comment]
./jasper.py
Traceback (most recent call last):
  File "./jasper.py", line 12, in <module>
    from client import tts
  File "/home/pi/jasper/client/tts.py", line 41, in <module>
    import diagnose
  File "/home/pi/jasper/client/diagnose.py", line 9, in <module>
    import pip.req
ImportError: No module named req
================
I reinstalled pip by easy-install but not solved
i saw this problem many times when i searched but coudl't find any solution
please help me
thanks a lot

**Comment by G10DRAS** [comment]
try
sudo python -m pip install --upgrade pip==9.0.3

**Comment by ahmadasadi** [comment]
hi thanks for your reply
i did it :
 sudo python -m pip install --upgrade pip==9.0.3
Looking in indexes: https://pypi.python.org/simple, https://www.piwheels.org/simple
Collecting pip==9.0.3
  Downloading https://files.pythonhosted.org/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl (1.4MB)
    100% |????????????????????????????????| 1.4MB 695kB/s
Installing collected packages: pip
  Found existing installation: pip 10.0.0
    Uninstalling pip-10.0.0:
      Successfully uninstalled pip-10.0.0
Successfully installed pip-9.0.3
You are using pip version 9.0.3, however version 10.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pi@raspberrypi:~ $ cd jasper/
pi@raspberrypi:~/jasper $ python jasper.py
No handlers could be found for logger "cmuclmtk"
Traceback (most recent call last):
  File "jasper.py", line 34, in <module>
    from client.mic import Mic
  File "/home/pi/jasper/client/mic.py", line 9, in <module>
    import pyaudio
ImportError: No module named pyaudio

but now i have another problem please help me again
thanks a lot

**Comment by G10DRAS** [comment]
Make sure you have downloaded the correct acoustic model and set the correct path.
Else download the latest acoustic model from cmusphinx source forge site into your home dir and set the path to it in profile.yml

**Comment by G10DRAS** [comment]
Install pyaudio

**Comment by ahmadasadi** [comment]
hi thanks a lot for your help.
i am on raspbian-stretch raspberry pi 3 model B.
after some debug now i have these  problems:

1-
python jasper.py
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:root:Error occured!
Traceback (most recent call last):
  File "jasper.py", line 146, in <module>
    app = Jasper()
  File "jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 42, in get_instance
    instance = cls(**config)
  File "/home/pi/jasper/client/stt.py", line 126, in __init__
    **vocabulary.decoder_kwargs)
TypeError: __init__() got an unexpected keyword argument 'hmm'

------------------
and this is my profile:
carrier: Toronto
first_name: ahmad
gmail_password: ''
last_name: asadi
location: Toronto
phone_number: ''
prefers_email: true
stt_engine: sphinx
pocketsphinx:
     fst_model: '/home/pi/jasper/client/phonetisaurus/g014b2b.fst'
     hmm_dir: '/usr/local/share/pocketsphinx-0.8/model/hmm/en_US/hub4wsj_sc_8k'
tts_engine: google-tts
before "fst_model" and "hmm_dir" lines are some spaces but i don't know why its not displayed here.
and  the path of hub4wsj_sc_8k' is correct.

i read "How to implement PocketSphinx 5prealpha in Jasper #343"
but i couldn't solve the problem.
and i installed it but i dont know how to use it instead of sphinx0.8 in jasper ,pls send me command for this.

2- also i have another problem :
sudo apt-get update
Get:1 http://ftp.debian.org/debian experimental InRelease [107 kB]
Hit:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Ign:1 http://ftp.debian.org/debian experimental InRelease
Get:3 http://archive.raspberrypi.org/debian stretch InRelease [25.3 kB]
Fetched 133 kB in 2s (55.1 kB/s)
Reading package lists... Done
W: GPG error: http://ftp.debian.org/debian experimental InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
W: The repository 'http://ftp.debian.org/debian experimental InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
what should i do for this new problem.

please help me again.
thanks a lot.

**Comment by Seanseattle** [comment]
@ahmadasadi ，I meet the same problem too.TypeError: init() got an unexpected keyword argument 'hmm'.
this soluton may help you
https://stackoverflow.com/questions/36105566/why-is-python-pocketsphinx-giving-typeerror.
I go to the github download model dir,it seems to can work.
