### ISSUE TITLE
Need help about jasper

### ISSUE THREAD

**Issue by zack2213** [jasperproject/jasper-client#684]
RROR:apscheduler.executors.default:Job "Notifier.gather (trigger: interval[0:00:30], next run at: 2018-06-01 14:15:23 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 108, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/jasper/client/notifier.py", line 39, in gather
    [client.run() for client in self.notifiers]
  File "/home/pi/jasper/client/notifier.py", line 18, in run
    self.timestamp = self.gather(self.timestamp)
  File "/home/pi/jasper/client/notifier.py", line 43, in handleEmailNotifications
    emails = Gmail.fetchUnreadEmails(self.profile, since=lastDate)
  File "/home/pi/jasper/client/modules/Gmail.py", line 63, in fetchUnreadEmails
    conn.login(profile['gmail_address'], profile['gmail_password'])
  File "/usr/lib/python2.7/imaplib.py", line 507, in login
    raise self.error(dat[-1])
error: Empty username or password. g40-v6mb41438488ywk
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['IN']
INFO:client.stt:Transcribed: ['IN']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['IN']
INFO:client.stt:Transcribed: ['IN']
INFO:client.stt:Transcribed: ['IN']
INFO:client.stt:Transcribed: ['IN']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['IN']
INFO:client.stt:Transcribed: ['']
ERROR:apscheduler.executors.default:Job "Notifier.gather (trigger: interval[0:00:30], next run at: 2018-06-01 14:15:53 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 108, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/jasper/client/notifier.py", line 39, in gather
    [client.run() for client in self.notifiers]
  File "/home/pi/jasper/client/notifier.py", line 18, in run
    self.timestamp = self.gather(self.timestamp)
  File "/home/pi/jasper/client/notifier.py", line 43, in handleEmailNotifications
    emails = Gmail.fetchUnreadEmails(self.profile, since=lastDate)
  File "/home/pi/jasper/client/modules/Gmail.py", line 63, in fetchUnreadEmails
    conn.login(profile['gmail_address'], profile['gmail_password'])
  File "/usr/lib/python2.7/imaplib.py", line 507, in login
    raise self.error(dat[-1])
error: Empty username or password. m68-v6mb261731760yba
INFO:client.stt:Transcribed: ['IN']

**Comment by dedenker** [comment]
The error states "Empty username or password".
So check these.

**Comment by zack2213** [comment]
So how to edit username or password.....do i need using sudo nano ~/.jasper/profile.yml???please guide me....im so newbie in python...

**Comment by dedenker** [comment]
Yes. RTFM.
Fill in the information in the profile.yml or disable it. Same file.
All is documented.

**Comment by zack2213** [comment]
pi@raspberrypi ~/jasper $ python jasper.py
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
ERROR:apscheduler.executors.default:Job "Notifier.gather (trigger: interval[0:00:30], next run at: 2018-06-02 09:45:37 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 108, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/jasper/client/notifier.py", line 39, in gather
    [client.run() for client in self.notifiers]
  File "/home/pi/jasper/client/notifier.py", line 18, in run
    self.timestamp = self.gather(self.timestamp)
  File "/home/pi/jasper/client/notifier.py", line 43, in handleEmailNotifications
    emails = Gmail.fetchUnreadEmails(self.profile, since=lastDate)
  File "/home/pi/jasper/client/modules/Gmail.py", line 63, in fetchUnreadEmails
    conn.login(profile['gmail_address'], profile['gmail_password'])
  File "/usr/lib/python2.7/imaplib.py", line 507, in login
    raise self.error(dat[-1])
error: [ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)



thanks man....but i got new error this...im using logitech usb earphone+microphone.....

**Comment by dedenker** [comment]
I only see an error in the email module.
Try to disable it (read the documentarion on how to disable email).
And restart, i do not see an error with any sound device.
