### ISSUE TITLE
Jasper not running right

### ISSUE THREAD

**Issue by InNeedOfHelp** [jasperproject/jasper-client#685]
hi, i started this project at the start of the week creating a magic mirror and one of the next steps of mine was to add a voice like siri, I added jasper but when i type in the command:

`python /home/pi/jasper/jasper.py`

This message comes up:

```
No handlers could be found for logger "cmuclmtk"
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 269, in _compile_vocabulary
    vocabulary = self._compile_languagemodel(text, self.languagemodel_file)
  File "/home/pi/jasper/client/vocabcompiler.py", line 290, in _compile_languagemodel
    cmuclmtk.text2vocab(text, vocab_file)
NameError: global name 'cmuclmtk' is not defined
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
NameError: global name 'cmuclmtk' is not defined
```

I am new to this and have tried to find  some sort of solution online but am totally stuck, could some one help me with this please?

**Comment by G10DRAS** [comment]
Install cmuclmtk

**Comment by InNeedOfHelp** [comment]
If you don't mind could you point me in the right direction as to where I would be able to install it through a command on the Pi?

**Comment by G10DRAS** [comment]
http://jasperproject.github.io/documentation/installation/

**Comment by G10DRAS** [comment]
Also install dependecies from

https://github.com/jasperproject/jasper-client/blob/master/client/requirements.txt
