### ISSUE TITLE
text2wfreq

### ISSUE THREAD

**Issue by tyolotech** [jasperproject/jasper-client#690]
pi@raspberrypi:~ $ /home/pi/jasper/jasper.py
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 269, in _compile_vocabulary
    vocabulary = self._compile_languagemodel(text, self.languagemodel_file)
  File "/home/pi/jasper/client/vocabcompiler.py", line 290, in _compile_languagemodel
    cmuclmtk.text2vocab(text, vocab_file)
  File "/usr/local/lib/python2.7/dist-packages/cmuclmtk/__init__.py", line 485, in text2vocab
    text2wfreq(text, wfreq_file, **text2wfreq_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cmuclmtk/__init__.py", line 114, in text2wfreq
    raise ConversionError("'%s' returned with non-zero exit status '%s'" % (cmd[0], exitcode))
ConversionError: 'text2wfreq' returned with non-zero exit status '127'
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
ConversionError: 'text2wfreq' returned with non-zero exit status '127'

Please help me

**Comment by G10DRAS** [comment]
Install cmuclmtk pkg.
