### ISSUE TITLE
psphinx - error on RPI, no error when using SSH? | optimize audio input? | creating langmodels for sphix?

### ISSUE THREAD

**Issue by PtFisch** [jasperproject/jasper-client#691]
Hello and thanks for bothering with this issue(s):

1)
I installed Jasper somewhat successfully (using the dev-branch) with Pocketsphinx (**5prealpha**) for STT and Flite for TTS. Now I startet Jasper via SSH and everything worked as expected, however, when starting Jasper directly in the Pi-Console (raspbian stretch with Desktop) the debug information tells me that Pocketsphinx is not installed:

```
pi@raspberrypi:~ $ cd /home/pi/jasper-client/
pi@raspberrypi:~/jasper-client $ ./Jasper.py --debug
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
DEBUG:jasper.application:Trying to read config file: '/home/pi/.jasper/profile.yml'
WARNING:jasper.application:language not specified in profile, using 'en-US'
INFO:jasper.application:audio_engine not specified in profile, using defaults.
DEBUG:jasper.application:Using Audio engine 'pyaudio'
DEBUG:jasper.application:Using STT engine 'sphinx'
DEBUG:jasper.application:Using passive STT engine 'sphinx'
DEBUG:jasper.application:Using TTS engine 'flite-tts'
INFO:jasper.application:Using keyword 'Jasper'
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/speechhandler/joke
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/speechhandler/joke/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: joke 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/speechhandler/life
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/speechhandler/life/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: life 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/speechhandler/notifications
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/speechhandler/notifications/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: notifications 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/speechhandler/birthday
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/speechhandler/birthday/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: birthday 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/speechhandler/clock
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/speechhandler/clock/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: clock 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/speechhandler/mpdcontrol
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/speechhandler/mpdcontrol/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: mpdcontrol 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/speechhandler/gmail
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/speechhandler/gmail/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: gmail 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/speechhandler/news
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/speechhandler/news/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: news 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/speechhandler/unclear
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/speechhandler/unclear/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: unclear 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/speechhandler/hackernews
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/speechhandler/hackernews/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: hn 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/speechhandler/weather
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/speechhandler/weather/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: weather 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/tts/google-tts
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/tts/google-tts/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: google-tts 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/tts/ivona-tts
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/tts/ivona-tts/plugin.info' parsed successfully!
WARNING:jasper.pluginstore:Plugin at '/home/pi/jasper-client/plugins/tts/ivona-tts' skipped! (Reason: No module named pyvona)
Traceback (most recent call last):
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 156, in detect_plugins
    plugin_info = self.parse_plugin(root)
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 195, in parse_plugin
    self._categories_map.values())
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 51, in parse_plugin_class
    ("py", "r", imp.PKG_DIRECTORY))
  File "/home/pi/jasper-client/plugins/tts/ivona-tts/__init__.py", line 2, in <module>
    from .ivona import IvonaTTSPlugin
  File "/home/pi/jasper-client/plugins/tts/ivona-tts/ivona.py", line 4, in <module>
    import pyvona
ImportError: No module named pyvona
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/tts/flite-tts
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/tts/flite-tts/plugin.info' parsed successfully!
DEBUG:jasper.diagnose:Checking executable 'flite'...
DEBUG:jasper.diagnose:Executable 'flite' found: '/usr/bin/flite'
DEBUG:jasper.pluginstore:Found valid plugin: flite-tts 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/tts/mstranslator-tts
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/tts/mstranslator-tts/plugin.info' parsed successfully!
WARNING:jasper.pluginstore:Plugin at '/home/pi/jasper-client/plugins/tts/mstranslator-tts' skipped! (Reason: No module named mstranslator)
Traceback (most recent call last):
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 156, in detect_plugins
    plugin_info = self.parse_plugin(root)
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 195, in parse_plugin
    self._categories_map.values())
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 51, in parse_plugin_class
    ("py", "r", imp.PKG_DIRECTORY))
  File "/home/pi/jasper-client/plugins/tts/mstranslator-tts/__init__.py", line 2, in <module>
    from .plugin import MicrosoftTranslatorTTSPlugin
  File "/home/pi/jasper-client/plugins/tts/mstranslator-tts/plugin.py", line 2, in <module>
    import mstranslator
ImportError: No module named mstranslator
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/tts/osx-tts
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/tts/osx-tts/plugin.info' parsed successfully!
WARNING:jasper.pluginstore:Plugin at '/home/pi/jasper-client/plugins/tts/osx-tts' skipped! (Reason: Invalid platform!)
Traceback (most recent call last):
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 156, in detect_plugins
    plugin_info = self.parse_plugin(root)
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 195, in parse_plugin
    self._categories_map.values())
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 51, in parse_plugin_class
    ("py", "r", imp.PKG_DIRECTORY))
  File "/home/pi/jasper-client/plugins/tts/osx-tts/__init__.py", line 2, in <module>
    from .osx import MacOSXTTSPlugin
  File "/home/pi/jasper-client/plugins/tts/osx-tts/osx.py", line 13, in <module>
    raise ImportError('Invalid platform!')
ImportError: Invalid platform!
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/tts/festival-tts
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/tts/festival-tts/plugin.info' parsed successfully!
DEBUG:jasper.diagnose:Checking executable 'text2wave'...
DEBUG:jasper.diagnose:Executable 'text2wave' not found
WARNING:jasper.pluginstore:Plugin at '/home/pi/jasper-client/plugins/tts/festival-tts' skipped! (Reason: Executables "text2wave" and/or  "festival" not found!)
Traceback (most recent call last):
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 156, in detect_plugins
    plugin_info = self.parse_plugin(root)
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 195, in parse_plugin
    self._categories_map.values())
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 51, in parse_plugin_class
    ("py", "r", imp.PKG_DIRECTORY))
  File "/home/pi/jasper-client/plugins/tts/festival-tts/__init__.py", line 2, in <module>
    from .festival import FestivalTTSPlugin
  File "/home/pi/jasper-client/plugins/tts/festival-tts/festival.py", line 10, in <module>
    raise ImportError('Executables "text2wave" and/or  "festival" not found!')
ImportError: Executables "text2wave" and/or  "festival" not found!
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/tts/espeak-tts
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/tts/espeak-tts/plugin.info' parsed successfully!
DEBUG:jasper.diagnose:Checking executable 'espeak'...
DEBUG:jasper.diagnose:Executable 'espeak' not found
WARNING:jasper.pluginstore:Plugin at '/home/pi/jasper-client/plugins/tts/espeak-tts' skipped! (Reason: espeak executable not found!)
Traceback (most recent call last):
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 156, in detect_plugins
    plugin_info = self.parse_plugin(root)
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 195, in parse_plugin
    self._categories_map.values())
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 51, in parse_plugin_class
    ("py", "r", imp.PKG_DIRECTORY))
  File "/home/pi/jasper-client/plugins/tts/espeak-tts/__init__.py", line 2, in <module>
    from .espeak import EspeakTTSPlugin
  File "/home/pi/jasper-client/plugins/tts/espeak-tts/espeak.py", line 11, in <module>
    raise ImportError("espeak executable not found!")
ImportError: espeak executable not found!
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/tts/cereproc-tts
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/tts/cereproc-tts/plugin.info' parsed successfully!
WARNING:jasper.pluginstore:Plugin at '/home/pi/jasper-client/plugins/tts/cereproc-tts' skipped! (Reason: No module named suds)
Traceback (most recent call last):
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 156, in detect_plugins
    plugin_info = self.parse_plugin(root)
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 195, in parse_plugin
    self._categories_map.values())
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 51, in parse_plugin_class
    ("py", "r", imp.PKG_DIRECTORY))
  File "/home/pi/jasper-client/plugins/tts/cereproc-tts/__init__.py", line 2, in <module>
    from .cereproc import CereprocTTSPlugin
  File "/home/pi/jasper-client/plugins/tts/cereproc-tts/cereproc.py", line 3, in <module>
    import suds
ImportError: No module named suds
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/tts/pico-tts
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/tts/pico-tts/plugin.info' parsed successfully!
DEBUG:jasper.diagnose:Checking executable 'pico2wave'...
DEBUG:jasper.diagnose:Executable 'pico2wave' not found
WARNING:jasper.pluginstore:Plugin at '/home/pi/jasper-client/plugins/tts/pico-tts' skipped! (Reason: Executable 'pico2wave' not found!)
Traceback (most recent call last):
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 156, in detect_plugins
    plugin_info = self.parse_plugin(root)
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 195, in parse_plugin
    self._categories_map.values())
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 51, in parse_plugin_class
    ("py", "r", imp.PKG_DIRECTORY))
  File "/home/pi/jasper-client/plugins/tts/pico-tts/__init__.py", line 2, in <module>
    from .pico import PicoTTSPlugin
  File "/home/pi/jasper-client/plugins/tts/pico-tts/pico.py", line 13, in <module>
    raise ImportError("Executable '%s' not found!" % EXECUTABLE)
ImportError: Executable 'pico2wave' not found!
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/tts/mary-tts
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/tts/mary-tts/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: mary-tts 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/audioengine/pyaudio-ae
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/audioengine/pyaudio-ae/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: pyaudio 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/audioengine/alsa-ae
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/audioengine/alsa-ae/plugin.info' parsed successfully!
WARNING:jasper.pluginstore:Plugin at '/home/pi/jasper-client/plugins/audioengine/alsa-ae' skipped! (Reason: No module named alsaaudio)
Traceback (most recent call last):
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 156, in detect_plugins
    plugin_info = self.parse_plugin(root)
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 195, in parse_plugin
    self._categories_map.values())
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 51, in parse_plugin_class
    ("py", "r", imp.PKG_DIRECTORY))
  File "/home/pi/jasper-client/plugins/audioengine/alsa-ae/__init__.py", line 2, in <module>
    from .alsaaudioengine import AlsaAudioEnginePlugin
  File "/home/pi/jasper-client/plugins/audioengine/alsa-ae/alsaaudioengine.py", line 4, in <module>
    import alsaaudio
ImportError: No module named alsaaudio
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/stt/witai-stt
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/stt/witai-stt/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: witai-stt 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/stt/pocketsphinx-stt
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/stt/pocketsphinx-stt/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: sphinx 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/stt/kaldigstserver-stt
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/stt/kaldigstserver-stt/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: kaldigstserver-stt 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/stt/julius-stt
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/stt/julius-stt/plugin.info' parsed successfully!
DEBUG:jasper.diagnose:Checking executable 'julius'...
DEBUG:jasper.diagnose:Executable 'julius' not found
WARNING:jasper.pluginstore:Plugin at '/home/pi/jasper-client/plugins/stt/julius-stt' skipped! (Reason: Can't find julius executable)
Traceback (most recent call last):
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 156, in detect_plugins
    plugin_info = self.parse_plugin(root)
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 195, in parse_plugin
    self._categories_map.values())
  File "/home/pi/jasper-client/jasper/pluginstore.py", line 51, in parse_plugin_class
    ("py", "r", imp.PKG_DIRECTORY))
  File "/home/pi/jasper-client/plugins/stt/julius-stt/__init__.py", line 2, in <module>
    from .julius import JuliusSTTPlugin
  File "/home/pi/jasper-client/plugins/stt/julius-stt/julius.py", line 10, in <module>
    raise ImportError("Can't find julius executable")
ImportError: Can't find julius executable
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/stt/google-stt
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/stt/google-stt/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: google 1.0.0
DEBUG:jasper.pluginstore:Found plugin candidate at: /home/pi/jasper-client/plugins/stt/att-stt
DEBUG:jasper.pluginstore:Plugin info file '/home/pi/jasper-client/plugins/stt/att-stt/plugin.info' parsed successfully!
DEBUG:jasper.pluginstore:Found valid plugin: att-stt 1.0.0
INFO:pyaudio_1_0_0.pyaudioengine:Initializing PyAudio. ALSA/Jack error messages that pop up during this process are normal and can usually be safely ignored.
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
INFO:pyaudio_1_0_0.pyaudioengine:Initialization of PyAudio engine finished
DEBUG:pyaudio_1_0_0.pyaudioengine:Found 10 PyAudio devices
WARNING:jasper.application:input_device not specified in profile, defaulting to 'default' (Possible values: usb-audio-device-hw-00, sysdefault, spdif, default)
DEBUG:pyaudio_1_0_0.pyaudioengine:Found 10 PyAudio devices
DEBUG:pyaudio_1_0_0.pyaudioengine:Found 10 PyAudio devices
WARNING:jasper.application:output_device not specified in profile, defaulting to 'default' (Possible values: usb-audio-device-hw-00, bcm2835-alsa-hw-10, bcm2835-alsa-iec958-hdmi, sysdefault, front, surround40, iec958, spdif, dmix, default)
DEBUG:pyaudio_1_0_0.pyaudioengine:Found 10 PyAudio devices
WARNING:jasper.application:Plugin 'weather' skipped! (Reason: Weather location not configured!)
Traceback (most recent call last):
  File "/home/pi/jasper-client/jasper/application.py", line 179, in __init__
    plugin = info.plugin_class(info, self.config)
  File "/home/pi/jasper-client/plugins/speechhandler/weather/weather.py", line 151, in __init__
    raise ValueError('Weather location not configured!')
ValueError: Weather location not configured!
Traceback (most recent call last):
  File "./Jasper.py", line 5, in <module>
    jasper.main()
  File "/home/pi/jasper-client/jasper/__main__.py", line 48, in main
    batch_file=p_args.batch_file)
  File "/home/pi/jasper-client/jasper/application.py", line 202, in __init__
    self.config)
  File "/home/pi/jasper-client/plugins/stt/pocketsphinx-stt/sphinxplugin.py", line 38, in __init__
    raise ImportError("Pocketsphinx not installed!")
ImportError: Pocketsphinx not installed!
pi@raspberrypi:~/jasper-client $ 
```

Is this in any way normal? If yes, how is it explainable and is it possible correct that?

2)
While installing Jasper and doing some research, I often read, that audio samples for STT were recordet at 16kHz, making 44.1kHz and 48kHz audio input rather inaccurate. Is it possible to remedy that without buying new hardware? If yes, how (e.g. code) and where (e.g. precise code part of a file).
Are there other steps to take, to optimze Pocketsphinx, like using longer keywords. (Running Jasper completely offline is important to my projects)

3)
The [Tutorial](https://wolfpaulus.com/embedded/raspberrypi2-sr/) explaines, how to create Wordfile, pronunciation dictionary and language model.
I am uncertain how to achieve the same with Jasper. There are (again, dev-branch) the jasper/data/standard_phrases (not containing "JASPER"). 
So which files do I have to edit in which way, to change the keywords and further the welcoming-message ("How can I be of service") if this is also possible.
What do I need to pay attention to, when creating a new model?

I would really appreciate, if someone is able to answer a question or having some advice.
Thank you in advance!

**Comment by PtFisch** [comment]
I solved issue 1:
There were still remains from my old Jasper-installation (Main-Branch).
I uninstalled Sphinxbase and Pocketsphinx in pip and fully removed my old Jasper-folder.
Now everything works fine, when starting directly from the Pi console.

I am still eager for input on issue 2 and 3.

**Comment by G10DRAS** [comment]
2. See function `def _write_frames_to_file(self, frames):` code at line 111.
3. No need to create pronunciation dictionary and language model, Jasper will create them for you.
   Keyword you can chnge in profile.yml `keyword: 'COMPUTER'`

**Comment by PtFisch** [comment]
Thanks for your answers. Found and successfully changed both.
