### ISSUE TITLE
Debian Stretch python 2.7 

### ISSUE THREAD

**Issue by mrFroggy** [jasperproject/jasper-client#692]
When running python2.7 on populate this error occurs 
`
/jasper/client$ python2.7 populate.py
Welcome to the profile populator. If, at any step, you'd prefer not to enter the requested information, just hit 'Enter' with a blank field to continue.
Traceback (most recent call last):
  File "populate.py", line 146, in <module>
    run()
  File "populate.py", line 26, in run
    simple_request('first_name', 'First name')
  File "populate.py", line 19, in simple_request
    input = input(cleanVar + ": ")
UnboundLocalError: local variable 'input' referenced before assignment

`

**Comment by G10DRAS** [comment]
Or else you can manually create profile.yml and put that in place.

**Comment by netzulo** [comment]
``` python
UnboundLocalError: local variable 'input' referenced before assignment
```
why not PR this somebody , @G10DRAS , @mrFroggy

**Comment by G10DRAS** [comment]
No point in creating a useless PR. I guess project is already abandoned.
