### ISSUE TITLE
No module named pyaudio

### ISSUE THREAD

**Issue by ARC1152018** [jasperproject/jasper-client#705]
After installing and configuring Jasper with google enginee for both STT and TTS, I tried to use Jasper but I got this:

** /home/pi/jasper//jasper.py
No handlers could be found for logger "cmuclmtk"
Traceback (most recent call last):
  File "/home/pi/jasper/jasper/jasper.py", line 34, in <module>
    from client.mic import Mic
  File "/home/pi/jasper/jasper/client/mic.py", line 9, in <module>
    import pyaudio
ImportError: No module named pyaudio
**

How can I solve it?

**Comment by ARC1152018** [comment]
sudo apt-get install python-pyaudio
