### ISSUE TITLE
Error while launching jasper.py

### ISSUE THREAD

**Issue by krithi96sk** [jasperproject/jasper-client#707]
I get the following errors when I try to open Jasper
```
pi@raspberrypi:~$ cd ~/jasper/
pi@raspberrypi:~/jasper$ ./jasper.py
No handlers could be found for logger "client.vocabcompiler"
Traceback (most recent call last):
  File "./jasper.py", line 16, in <module>
    from client.conversation import Conversation
  File "/home/pi/jasper/client/conversation.py", line 3, in <module>
    from notifier import Notifier
  File "/home/pi/jasper/client/notifier.py", line 4, in <module>
    from modules import Gmail
  File "/home/pi/jasper/client/modules/Gmail.py", line 5, in <module>
    from dateutil import parser
ImportError: No module named dateutil
```
My pip version is 9.0.3 and I'm using wit.ai with espeak.
Please advice.

**Comment by G10DRAS** [comment]
install python-dateutil
