### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rubann7** [jasperproject/jasper-client#711]
YOU: news
JASPER: Pulling up the news
ERROR:client.brain:Failed to execute module
Traceback (most recent call last):
  File "/root/jasper/client/brain.py", line 73, in query
    module.handle(text, self.mic, self.profile)
  File "/root/jasper/client/modules/News.py", line 48, in handle
  File "/root/jasper/client/modules/News.py", line 27, in getTopArticles
IndexError: list index out of range
JASPER: I'm sorry. I had some trouble with that operation. Please try again later.

**Comment by G10DRAS** [comment]
check the news URL at line 22 if that wrong !!

**Comment by appeacock** [comment]
The work on Jasper - specifically making it work as-is and refactoring to Python 3 is being conducted at https://github.com/aplawson/jasper-client -- including a tutorial on how to build it and/or deploy it with a custom Raspbian ISO image. //adam
