### ISSUE TITLE
Google TTS Engine not available

### ISSUE THREAD

**Issue by appeacock** [jasperproject/jasper-client#717]
On the off chance there is an active developer able to review versus redirecting to an equally inactive forum:
```
pi@raspberrypi:~ $ ~/jasper/jasper.py
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 105, in __init__
    tts_engine_class = tts.get_engine_by_slug(tts_engine_slug)
  File "/home/pi/jasper/client/tts.py", line 665, in get_engine_by_slug
    "missing dependencies, etc.)") % slug)
ValueError: TTS engine 'google-tts' is not available (due to missing dependencies, etc.)
```

Reproduced after 2 attempts to start Jasper with same TTS engine as well as AT&T method. Same error. Code fails and does not indicate any problems.

**Comment by appeacock** [comment]
profile.yml:
```carrier: txt.att.net
first_name: <scrub>
gmail_address: <scrub>
gmail_password: <scrub>
keys:
  GOOGLE_SPEECH: <scrub>
last_name: <scrub>
phone_number: '<scrub>'
prefers_email: true
stt_engine: google
tts_engine: google-tts
timezone: America/Los_Angeles
wmo_id: 72483
```

**Comment by mecparts** [comment]
As a test, does a local TTS engine work, say pico-tts?

**Comment by appeacock** [comment]
I've abandoned jasper as a project worth pursuing due to the number of unresolved issues and 5 years of no development activity. If I do pursue it, it will be as an offline fix-it project

**Comment by appeacock** [comment]
The work on Jasper - specifically making it work as-is and refactoring to Python 3 is being conducted at https://github.com/aplawson/jasper-client -- including a tutorial on how to build it and/or deploy it with a custom Raspbian ISO image. //adam
