### ISSUE TITLE
the error when I run jasper.py 

### ISSUE THREAD

**Issue by lijunwei19** [jasperproject/jasper-client#718]
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 42, in get_instance
    instance = cls(**config)
  File "/home/pi/jasper/client/stt.py", line 128, in __init__
    psConfig.set_string('-hmm', hmm_dir)
AttributeError: 'SwigPyObject' object has no attribute 'set_string'
swig/python detected a memory leak of type 'Config *', no destructor found.

I don't know the problem is caused by python swig or wrong way to the jasper installation process. Anyone could help me, thank you a lot.

**Comment by lijunwei19** [comment]
pi@raspberrypi:~$ swig -version

SWIG Version 3.0.12

Compiled with g++ [armv8l-unknown-linux-gnueabihf]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information

**Comment by lijunwei19** [comment]
1carrier: ####
first_name: ####
gmail_address: #####
gmail_password: #####
last_name: Li
phone_number: ''
prefers_email: true
stt_engine: sphinx
pocketsphinx:
  fst_model: '/home/pi/phonetisaurus/g014b2b.fst'
  hmm_dir: '/home/pi/pocketsphinx-0.8/model/hmm/en_US/hub4wsj_sc_8k'
timezone: America/New_York
tts_engine: espeak-tts
espeak-tts:
  voice: 'default+m3'
  pitch_adjustment: 40
  words_per_minute: 160

**Comment by appeacock** [comment]
The work on Jasper - specifically making it work as-is and refactoring to Python 3 is being conducted at https://github.com/aplawson/jasper-client -- including a tutorial on how to build it and/or deploy it with a custom Raspbian ISO image. //adam
