### ISSUE TITLE
Error after running jasper.py

### ISSUE THREAD

**Issue by zeesh1979** [jasperproject/jasper-client#722]
hi,
when i run jsper, its not running. below are logs:

pi@raspberrypi:~ $ /home/pi/jasper/jasper.py
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 151, in <module>
    app.run()
  File "/home/pi/jasper/jasper.py", line 121, in run
    conversation.handleForever()
  File "/home/pi/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/jasper/client/mic.py", line 110, in passiveListen
    frames_per_buffer=CHUNK)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9997] Invalid sample rate

below is my .asoudrc file (whenever i make changes to it, after reboot it goes back to same as below)
```
pcm.!default {
	type hw
	card 1
}

ctl.!default {
	type hw
	card 1
}
```
below my sound devices:
pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 1: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

below my /etc/asound.conf:
pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:0,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:1,0"
  }
}

**Comment by nikhilgg** [comment]
Did you find a solution? 

I've the same issue. I had set it up 8-9 months ago. Used to work. Restarted the pi today after a long time and face this issue when trying to use Jasper.

**Comment by zeesh1979** [comment]
Nops. I heard the project stopped and no updates coming now

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by appeacock** [comment]
The work is being continued at https://github.com/aplawson/jasper-client, specifically an update to Python3 and a tutorial on how to build it or deploy it with a custom Raspbian ISO image.  //adam

**Comment by zeesh1979** [comment]
Thanks. i have put the image from sourceforge to my RPi3b but its not booting (red led is continuous on). what could be wrong? my sd card card and rpi both are fine coz i used a working set for this

________________________________

**Comment by appeacock** [comment]
I would attach a monitor and watch the output while the rPI is booting. That will disclose many issues (and when they occur) during the boot-up process. //adam

**Comment by aplawson** [comment]
I would attach a monitor and monitor the output while the rPI is booting.
That will disclose many issues (and when they occur) during the boot-up
process. //adam

*Adam Peacock*

Principal Architect
Office: +1-916-794-5706

**Comment by appeacock** [comment]
Also there are two projects with an rPI image. https://sourceforge.net/projects/jasperproject has a stale/broken image. https://sourceforge.net/projects/jasperclient has an image that was tested in February or March of this year so much more current.

**Comment by zeesh1979** [comment]
Oh i had downloaded from 1st link. I will check other one. Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zeesh1979** [comment]
Hi,
I have flashed it to my SD and its up now. but how to run jasper now? i cannt seem to find any python or shell file to run

________________________________
